import StudioProtocol

/// Emits an instrumented Android test that queries Jetpack Compose's semantics tree.
public struct ComposeEspressoEmitter: StudioCodeEmitting {
    public init() {}

    public func generate(_ test: StudioAuthoredTest) throws -> StudioTestExportResult {
        guard let operations = test.compiledPlan?.toolOperations, operations.isEmpty == false else {
            throw TestCodeGeneratorError.missingCompiledPlan
        }
        let className = "\(TestIdentifierNaming.pascalCase(test.name))Test"
        let methodName = "test\(TestIdentifierNaming.pascalCase(test.name))"
        let body = try operations.map { try Self.statement(for: $0) }.joined(separator: "\n")

        let source = """
        import android.app.Activity
        import android.content.Intent
        import androidx.compose.ui.test.assertIsDisplayed
        import androidx.compose.ui.test.assertIsEnabled
        import androidx.compose.ui.test.assertIsNotDisplayed
        import androidx.compose.ui.test.assertTextEquals
        import androidx.compose.ui.test.hasContentDescription
        import androidx.compose.ui.test.hasTestTag
        import androidx.compose.ui.test.hasText
        import androidx.compose.ui.test.isFocused
        import androidx.compose.ui.test.junit4.v2.createEmptyComposeRule
        import androidx.compose.ui.test.onRoot
        import androidx.compose.ui.test.performClick
        import androidx.compose.ui.test.performTextInput
        import androidx.compose.ui.test.performTextReplacement
        import androidx.compose.ui.test.performTouchInput
        import androidx.compose.ui.test.swipeDown
        import androidx.compose.ui.test.swipeLeft
        import androidx.compose.ui.test.swipeRight
        import androidx.compose.ui.test.swipeUp
        import androidx.test.core.app.ActivityScenario
        import androidx.test.espresso.Espresso.pressBack
        import androidx.test.ext.junit.runners.AndroidJUnit4
        import androidx.test.platform.app.InstrumentationRegistry
        import org.junit.Rule
        import org.junit.Test
        import org.junit.runner.RunWith

        /**
         * Generated by amoo from the Studio test "\(test.name)". Edit freely — this file has no
         * dependency on amoo or the companion apps once generated.
         */
        @RunWith(AndroidJUnit4::class)
        class \(className) {
            @get:Rule
            val composeTestRule = createEmptyComposeRule()

            @Test
            fun \(methodName)() {
                val targetContext = InstrumentationRegistry.getInstrumentation().targetContext
                val launchIntent = requireNotNull(
                    targetContext.packageManager.getLaunchIntentForPackage(targetContext.packageName)
                ) { "No launcher activity found for ${targetContext.packageName}" }
                launchIntent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TASK)

                ActivityScenario.launch<Activity>(launchIntent).use {
        \(body)
                }
            }
        }
        """
        return StudioTestExportResult(fileName: "\(className).kt", source: source)
    }

    private static let indent = "        "

    // A direct switch keeps the supported Studio-tool-to-Compose mapping auditable in one place.
    // swiftlint:disable:next cyclomatic_complexity
    private static func statement(for operation: StudioToolOperation) throws -> String {
        switch operation.tool {
        case "tap_element":
            return try "\(indent)\(node(operation)).assertIsDisplayed().performClick()"
        case "set_text":
            guard let value = operation.arguments["value"] else {
                throw TestCodeGeneratorError.missingArgument(tool: operation.tool, argument: "value")
            }
            return try "\(indent)\(node(operation)).assertIsDisplayed().performTextReplacement(\(literal(value)))"
        case "type_text":
            guard let text = operation.arguments["text"] else {
                throw TestCodeGeneratorError.missingArgument(tool: operation.tool, argument: "text")
            }
            return "\(indent)composeTestRule.onNode(isFocused()).performTextInput(\(literal(text)))"
        case "swipe_in_direction", "scroll":
            // GestureDirection inverts scroll for us — see its documentation for why.
            let gesture = try gesture(for: operation)
            if operation.arguments["element_id"] != nil || operation.arguments["element_label"] != nil {
                let target = try node(operation, idKey: "element_id", labelKey: "element_label")
                return "\(indent)\(target).assertIsDisplayed().performTouchInput { \(gesture)() }"
            }
            return "\(indent)composeTestRule.onRoot().performTouchInput { \(gesture)() }"
        case "wait_for_element":
            return try waitStatement(operation)
        case "assert_visible":
            return try "\(indent)\(node(operation)).assertIsDisplayed()"
        case "assert_not_visible":
            // Visibility is weaker than non-existence: an off-screen node still satisfies this tool.
            return try "\(indent)\(node(operation)).assertIsNotDisplayed()"
        case "assert_text":
            guard let expected = operation.arguments["value"] ?? operation.arguments["expected"] else {
                throw TestCodeGeneratorError.missingArgument(tool: operation.tool, argument: "value")
            }
            return try "\(indent)\(node(operation)).assertTextEquals(\(literal(expected)))"
        case "assert_enabled":
            return try "\(indent)\(node(operation)).assertIsEnabled()"
        case "take_screenshot":
            return "\(indent)// take_screenshot: capture through the Android test runner when needed"
        case "press_back":
            return "\(indent)pressBack()"
        default:
            throw TestCodeGeneratorError.unsupportedTool(operation.tool)
        }
    }

    private static func waitStatement(_ operation: StudioToolOperation) throws -> String {
        let matcher = try semanticsMatcher(operation)
        let timeout = try timeoutMilliseconds(for: operation)
        return "\(indent)composeTestRule.waitUntil(timeoutMillis = \(timeout)L) { "
            + "composeTestRule.onAllNodes(\(matcher)).fetchSemanticsNodes().isNotEmpty() }"
    }

    private static func node(
        _ operation: StudioToolOperation,
        idKey: String = "id",
        labelKey: String = "label",
        containsTextKey: String = "contains_text"
    ) throws -> String {
        let matcher = try semanticsMatcher(
            operation,
            idKey: idKey,
            labelKey: labelKey,
            containsTextKey: containsTextKey
        )
        return "composeTestRule.onNode(\(matcher))"
    }

    private static func semanticsMatcher(
        _ operation: StudioToolOperation,
        idKey: String = "id",
        labelKey: String = "label",
        containsTextKey: String = "contains_text"
    ) throws -> String {
        if let id = operation.arguments[idKey] {
            return "hasTestTag(\(literal(id)))"
        }
        if let label = operation.arguments[labelKey] {
            return "hasContentDescription(\(literal(label)))"
        }
        if let text = operation.arguments[containsTextKey] {
            return "hasText(\(literal(text)), substring = true)"
        }
        throw TestCodeGeneratorError.missingArgument(tool: operation.tool, argument: "id, label, or contains_text")
    }

    private static func timeoutMilliseconds(for operation: StudioToolOperation) throws -> Int64 {
        guard let raw = operation.arguments["timeout_ms"] else { return 5000 }
        guard let value = Int64(raw), value > 0 else {
            throw TestCodeGeneratorError.invalidArgument(tool: operation.tool, argument: "timeout_ms", value: raw)
        }
        return value
    }

    private static func literal(_ value: String) -> String {
        var escaped = value
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
            .replacingOccurrences(of: "\n", with: "\\n")
            .replacingOccurrences(of: "\r", with: "\\r")
            .replacingOccurrences(of: "\t", with: "\\t")
        escaped = String(escaped.unicodeScalars.map { scalar -> String in
            guard scalar.value < 0x20 else { return String(scalar) }
            let hex = String(scalar.value, radix: 16)
            return "\\u\(String(repeating: "0", count: 4 - hex.count))\(hex)"
        }.joined())
        return "\"\(escaped)\""
    }

    /// Compose's touch-injection gesture name for this operation's direction.
    private static func gesture(for operation: StudioToolOperation) throws -> String {
        guard let raw = operation.arguments["direction"] else {
            throw TestCodeGeneratorError.missingArgument(tool: operation.tool, argument: "direction")
        }
        let direction = try GestureDirection.gestureDirection(for: operation.tool, rawDirection: raw)
        switch direction {
        case .up: return "swipeUp"
        case .down: return "swipeDown"
        case .left: return "swipeLeft"
        case .right: return "swipeRight"
        }
    }
}
