import StudioProtocol

/// Emits an instrumented Android test that queries Jetpack Compose's semantics tree.
public struct ComposeEspressoEmitter: StudioCodeEmitting {
    public init() {}

    // SwiftLint measures the generated Kotlin template as Swift function body lines.
    // swiftlint:disable:next function_body_length
    public func generate(_ test: StudioAuthoredTest) throws -> StudioTestExportResult {
        guard let operations = test.compiledPlan?.toolOperations, operations.isEmpty == false else {
            throw TestCodeGeneratorError.missingCompiledPlan
        }
        let className = "\(TestIdentifierNaming.pascalCase(test.name))Test"
        let methodName = "test\(TestIdentifierNaming.pascalCase(test.name))"
        let needsScrollHelper = operations.contains { Self.isUnscopedScroll($0) }
        let body = try operations.indices
            .map { index -> String in
                let next = index + 1 < operations.count ? operations[index + 1] : nil
                return try Self.statement(for: operations[index], next: next, context: test.testContext)
            }
            .joined(separator: "\n")
        // Statements sit inside `ActivityScenario.launch { }`, one level deeper than they are
        // emitted. Mirrors EspressoEmitter's launchedBody.
        let launchedBody = body.split(separator: "\n", omittingEmptySubsequences: false)
            .map { "    \($0)" }
            .joined(separator: "\n")
        let contextImports = TestHelperRendering.imports(for: test.testContext)
            .map { "import \($0)" }
            .joined(separator: "\n")
        let baseClass = test.testContext?.baseClass.map { " : \($0)" } ?? ""

        let source = """
        import android.app.Activity
        import android.content.Intent
        import androidx.compose.ui.semantics.SemanticsActions
        import androidx.compose.ui.semantics.SemanticsProperties
        import androidx.compose.ui.test.SemanticsMatcher
        import androidx.compose.ui.test.SemanticsNodeInteraction
        import androidx.compose.ui.test.assertIsDisplayed
        import androidx.compose.ui.test.assertIsEnabled
        import androidx.compose.ui.test.assertTextEquals
        import androidx.compose.ui.test.hasContentDescription
        import androidx.compose.ui.test.hasTestTag
        import androidx.compose.ui.test.hasText
        import androidx.compose.ui.test.isFocused
        import androidx.compose.ui.test.junit4.v2.createEmptyComposeRule
        import androidx.compose.ui.test.onRoot
        import androidx.compose.ui.test.performClick
        import androidx.compose.ui.test.performScrollToNode
        import androidx.compose.ui.test.performSemanticsAction
        import androidx.compose.ui.test.performTextInput
        import androidx.compose.ui.test.performTextReplacement
        import androidx.compose.ui.test.performTouchInput
        import androidx.compose.ui.test.swipeDown
        import androidx.compose.ui.test.swipeLeft
        import androidx.compose.ui.test.swipeRight
        import androidx.compose.ui.test.swipeUp
        import androidx.test.core.app.ActivityScenario
        import androidx.test.espresso.Espresso.pressBack
        import androidx.test.ext.junit.runners.AndroidJUnit4
        import androidx.test.platform.app.InstrumentationRegistry
        import org.junit.Rule
        import org.junit.Test
        import org.junit.runner.RunWith\(contextImports.isEmpty ? "" : "\n\(contextImports)")

        /**
         * Generated by amoo from the Studio test "\(test.name)". Edit freely — this file has no
         * dependency on amoo or the companion apps once generated.
         */
        @RunWith(AndroidJUnit4::class)
        class \(className)\(baseClass) {
            @get:Rule
            val composeTestRule = createEmptyComposeRule()
        \(needsScrollHelper ? Self.scrollHelper + "\n" : "")
            @Test
            fun \(methodName)() {
                val targetContext = InstrumentationRegistry.getInstrumentation().targetContext
                val launchIntent = requireNotNull(
                    targetContext.packageManager.getLaunchIntentForPackage(targetContext.packageName)
                ) { "No launcher activity found for ${targetContext.packageName}" }
                launchIntent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TASK)

                ActivityScenario.launch<Activity>(launchIntent).use {
        \(launchedBody)
                }
            }
        }
        """
        return StudioTestExportResult(fileName: "\(className).kt", source: source)
    }

    private static let indent = "        "

    private static func isUnscopedScroll(_ operation: StudioToolOperation) -> Bool {
        operation.tool == StudioTool.scroll.rawValue
            && operation.arguments["element_id"] == nil
            && operation.arguments["element_label"] == nil
    }

    /// Emitted once when an unscoped `scroll` is present.
    ///
    /// `performScrollToNode` (the value path — when the recorded step after the scroll targets an
    /// element) and `ScrollBy` (the fallback) are both semantics-driven, so neither depends on the
    /// scroll node's bounds — a LazyColumn's scroll node can report a zero-size rect, which makes a
    /// `performTouchInput` swipe a silent no-op. The container is chosen by scroll axis, largest by
    /// area, so a nested horizontal carousel never absorbs a vertical scroll.
    private static let scrollHelper: String = {
        let raw = """
        private fun scrollContainer(vertical: Boolean): SemanticsNodeInteraction {
            composeTestRule.waitForIdle()
            val axisKey = if (vertical) {
                SemanticsProperties.VerticalScrollAxisRange
            } else {
                SemanticsProperties.HorizontalScrollAxisRange
            }
            val targetId = composeTestRule
                .onAllNodes(SemanticsMatcher.keyIsDefined(axisKey), useUnmergedTree = true)
                .fetchSemanticsNodes()
                .filter { it.config.contains(SemanticsActions.ScrollBy) }
                .maxByOrNull { it.boundsInRoot.width * it.boundsInRoot.height }
                ?.id
                ?: error("No scrollable node on the current screen for the requested axis")
            return composeTestRule.onNode(
                SemanticsMatcher("scroll container id=" + targetId) { it.id == targetId },
                useUnmergedTree = true
            )
        }

        private fun scrollByViewport(vertical: Boolean, forward: Boolean) {
            val viewport = composeTestRule.onRoot().fetchSemanticsNode().boundsInRoot
            val extent = (if (vertical) viewport.height else viewport.width).takeIf { it > 0f } ?: 2000f
            val delta = if (forward) extent * 0.8f else -extent * 0.8f
            scrollContainer(vertical).performSemanticsAction(SemanticsActions.ScrollBy) {
                if (vertical) it(0f, delta) else it(delta, 0f)
            }
            composeTestRule.waitForIdle()
        }
        """
        return raw.split(separator: "\n", omittingEmptySubsequences: false)
            .map { $0.isEmpty ? "" : "    \($0)" }
            .joined(separator: "\n")
    }()

    // A direct switch keeps the supported Studio-tool-to-Compose mapping auditable in one place.
    // swiftlint:disable:next cyclomatic_complexity
    private static func statement(
        for operation: StudioToolOperation,
        next: StudioToolOperation?,
        context: StudioTestContext?
    ) throws -> String {
        if let helper = try TestHelperRendering.call(for: operation, context: context, literal: literal) {
            return "\(indent)\(helper)"
        }
        guard let tool = StudioTool(rawValue: operation.tool) else {
            throw TestCodeGeneratorError.unsupportedTool(operation.tool)
        }
        // No `default`: adding a StudioTool case must fail to compile here until it is handled.
        switch tool {
        case .tapElement:
            let target = try guardedNode(operation)
            return "\(target.wait)\n\(indent)\(target.node).assertIsDisplayed().performClick()"
        case .setText:
            guard let value = operation.arguments["value"] else {
                throw TestCodeGeneratorError.missingArgument(tool: operation.tool, argument: "value")
            }
            let target = try guardedNode(operation)
            return "\(target.wait)\n\(indent)\(target.node)"
                + ".assertIsDisplayed().performTextReplacement(\(literal(value)))"
        case .typeText:
            guard let text = operation.arguments["text"] else {
                throw TestCodeGeneratorError.missingArgument(tool: operation.tool, argument: "text")
            }
            let wait = try waitForNodePresent("isFocused()", timeout: timeoutMilliseconds(for: operation))
            return "\(wait)\n\(indent)composeTestRule.onNode(isFocused()).performTextInput(\(literal(text)))"
        case .swipeInDirection, .scroll:
            // GestureDirection inverts scroll for us — see its documentation for why.
            let gesture = try gesture(for: operation)
            if operation.arguments["element_id"] != nil || operation.arguments["element_label"] != nil {
                let target = try guardedNode(operation, idKey: "element_id", labelKey: "element_label")
                return "\(target.wait)\n\(indent)\(target.node)"
                    + ".assertIsDisplayed().performTouchInput { \(gesture)() }"
            }
            if tool == .scroll {
                // A coordinate swipe (on the root or on the scroll node) is unreliable in Compose:
                // it is not routed into the nested-scroll system from the root, and a LazyColumn's
                // scroll node can report zero bounds, making the gesture a no-op. Scroll via
                // semantics instead. `gesture` is the inverted swipe direction, so swipeUp/swipeLeft
                // mean "scroll forward".
                let vertical = gesture == "swipeUp" || gesture == "swipeDown"
                let forward = gesture == "swipeUp" || gesture == "swipeLeft"
                if let next, let target = try? Self.lookAheadMatcher(for: next) {
                    // A recorded scroll almost always exists to bring the next step's target on
                    // screen — scroll exactly until it is, which needs no distance guess.
                    return "\(indent)scrollContainer(vertical = \(vertical)).performScrollToNode(\(target))"
                }
                return "\(indent)scrollByViewport(vertical = \(vertical), forward = \(forward))"
            }
            return "\(indent)composeTestRule.onRoot().performTouchInput { \(gesture)() }"
        case .waitForElement:
            return try waitForNodePresent(semanticsMatcher(operation), timeout: timeoutMilliseconds(for: operation))
        case .assertVisible:
            let target = try guardedNode(operation)
            return "\(target.wait)\n\(indent)\(target.node).assertIsDisplayed()"
        case .assertNotVisible:
            // Poll until no node matches, so a control that is still animating out at the moment the
            // step runs does not fail the assertion. In a Compose tree an off-screen node in a lazy
            // container is already absent from the semantics tree, so this also covers "scrolled away".
            return try waitForNodeAbsent(semanticsMatcher(operation), timeout: timeoutMilliseconds(for: operation))
        case .assertText:
            guard let expected = operation.arguments["value"] ?? operation.arguments["expected"] else {
                throw TestCodeGeneratorError.missingArgument(tool: operation.tool, argument: "value")
            }
            let target = try guardedNode(operation)
            return "\(target.wait)\n\(indent)\(target.node).assertTextEquals(\(literal(expected)))"
        case .assertEnabled:
            let target = try guardedNode(operation)
            return "\(target.wait)\n\(indent)\(target.node).assertIsEnabled()"
        case .takeScreenshot:
            return "\(indent)// take_screenshot: capture through the Android test runner when needed"
        case .pressBack:
            return "\(indent)pressBack()"
        }
    }

    /// The semantics matcher for the element `next` acts on, when `next` is a step that targets one
    /// by id / label / text — used to turn a preceding `scroll` into a `performScrollToNode`. Steps
    /// with no positive target (a bare gesture, `press_back`, `assert_not_visible`, …) return nil so
    /// the scroll falls back to a distance-based `ScrollBy`.
    private static func lookAheadMatcher(for next: StudioToolOperation) throws -> String {
        let scrollToTargets = Set(
            [StudioTool.tapElement, .setText, .assertVisible, .assertText, .assertEnabled, .waitForElement]
                .map(\.rawValue)
        )
        guard scrollToTargets.contains(next.tool) else {
            throw TestCodeGeneratorError.unsupportedTool(next.tool)
        }
        return try semanticsMatcher(next)
    }

    /// A `waitUntil` that blocks until at least one node matches, plus the `onNode` handle to act on
    /// afterwards. Mirrors `EspressoEmitter`'s `waitUntilDisplayed` guard so a generated assertion or
    /// interaction tolerates the same load/transition delay the recording session waited out.
    private static func guardedNode(
        _ operation: StudioToolOperation,
        idKey: String = "id",
        labelKey: String = "label",
        containsTextKey: String = "contains_text"
    ) throws -> (wait: String, node: String) {
        let matcher = try semanticsMatcher(
            operation,
            idKey: idKey,
            labelKey: labelKey,
            containsTextKey: containsTextKey
        )
        let wait = try waitForNodePresent(matcher, timeout: timeoutMilliseconds(for: operation))
        return (wait, "composeTestRule.onNode(\(matcher))")
    }

    private static func waitForNodePresent(_ matcher: String, timeout: Int64) -> String {
        "\(indent)composeTestRule.waitUntil(timeoutMillis = \(timeout)L) { "
            + "composeTestRule.onAllNodes(\(matcher)).fetchSemanticsNodes().isNotEmpty() }"
    }

    private static func waitForNodeAbsent(_ matcher: String, timeout: Int64) -> String {
        "\(indent)composeTestRule.waitUntil(timeoutMillis = \(timeout)L) { "
            + "composeTestRule.onAllNodes(\(matcher)).fetchSemanticsNodes().isEmpty() }"
    }

    private static func semanticsMatcher(
        _ operation: StudioToolOperation,
        idKey: String = "id",
        labelKey: String = "label",
        containsTextKey: String = "contains_text"
    ) throws -> String {
        if let id = operation.arguments[idKey] {
            return "hasTestTag(\(literal(id)))"
        }
        if let label = operation.arguments[labelKey] {
            return "hasContentDescription(\(literal(label)))"
        }
        if let text = operation.arguments[containsTextKey] {
            return "hasText(\(literal(text)), substring = true)"
        }
        throw TestCodeGeneratorError.missingArgument(tool: operation.tool, argument: "id, label, or contains_text")
    }

    private static func timeoutMilliseconds(for operation: StudioToolOperation) throws -> Int64 {
        guard let raw = operation.arguments["timeout_ms"] else { return 5000 }
        guard let value = Int64(raw), value > 0 else {
            throw TestCodeGeneratorError.invalidArgument(tool: operation.tool, argument: "timeout_ms", value: raw)
        }
        return value
    }

    private static func literal(_ value: String) -> String {
        var escaped = value
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
            .replacingOccurrences(of: "\n", with: "\\n")
            .replacingOccurrences(of: "\r", with: "\\r")
            .replacingOccurrences(of: "\t", with: "\\t")
        escaped = String(escaped.unicodeScalars.map { scalar -> String in
            guard scalar.value < 0x20 else { return String(scalar) }
            let hex = String(scalar.value, radix: 16)
            return "\\u\(String(repeating: "0", count: 4 - hex.count))\(hex)"
        }.joined())
        return "\"\(escaped)\""
    }

    /// Compose's touch-injection gesture name for this operation's direction.
    private static func gesture(for operation: StudioToolOperation) throws -> String {
        guard let raw = operation.arguments["direction"] else {
            throw TestCodeGeneratorError.missingArgument(tool: operation.tool, argument: "direction")
        }
        let direction = try GestureDirection.gestureDirection(for: operation.tool, rawDirection: raw)
        switch direction {
        case .up: return "swipeUp"
        case .down: return "swipeDown"
        case .left: return "swipeLeft"
        case .right: return "swipeRight"
        }
    }
}
