import StudioProtocol

// Emits a Kotlin Espresso instrumented test — no amoo companion app involved at run time.
//
// Companion-normalized element `id`s are runtime resource names or content descriptions as strings;
// idiomatic Espresso (`withId(R.id.foo)`) needs a compile-time `R` reference this generator can't
// resolve. Generated code falls back to a small `hasResourceEntryName` matcher instead of `R.id`,
// with a comment pointing at the substitution — swap it for `withId(R.id...)` where convenient.
// swiftlint:disable:next type_body_length
public struct EspressoEmitter: StudioCodeEmitting {
    public init() {}

    // SwiftLint measures the generated Kotlin template as Swift function body lines.
    // swiftlint:disable:next function_body_length
    public func generate(_ test: StudioAuthoredTest) throws -> StudioTestExportResult {
        guard let operations = test.compiledPlan?.toolOperations, operations.isEmpty == false else {
            throw TestCodeGeneratorError.missingCompiledPlan
        }
        let pascalName = TestIdentifierNaming.pascalCase(test.name)
        let className = "\(pascalName)Test"
        let methodName = pascalName.prefix(1).lowercased() + pascalName.dropFirst()
        let body = try operations.map { try Self.statement(for: $0, context: test.testContext) }.joined(separator: "\n")
        let launchedBody = body.split(separator: "\n", omittingEmptySubsequences: false)
            .map { "    \($0)" }
            .joined(separator: "\n")
        let needsResourceNameMatcher = operations.contains {
            ($0.arguments["id"] != nil || $0.arguments["element_id"] != nil) && [
                "tap_element",
                "set_text",
                "wait_for_element",
                "assert_visible",
                "assert_not_visible",
                "assert_text",
                "assert_value",
                "assert_enabled"
            ].contains($0.tool)
        }
        let contextImports = TestHelperRendering.imports(for: test.testContext)
            .map { "import \($0)" }
            .joined(separator: "\n")
        let baseClass = test.testContext?.baseClass.map { " : \($0)" } ?? ""

        let source = """
        import android.app.Activity
        import android.content.Intent
        import android.os.SystemClock
        import android.view.View
        import androidx.test.core.app.ActivityScenario
        import androidx.test.espresso.Espresso.onView
        import androidx.test.espresso.Espresso.pressBack
        import androidx.test.espresso.PerformException
        import androidx.test.espresso.UiController
        import androidx.test.espresso.ViewAction
        import androidx.test.espresso.action.ViewActions.click
        import androidx.test.espresso.action.ViewActions.replaceText
        import androidx.test.espresso.action.ViewActions.swipeDown
        import androidx.test.espresso.action.ViewActions.swipeLeft
        import androidx.test.espresso.action.ViewActions.swipeRight
        import androidx.test.espresso.action.ViewActions.swipeUp
        import androidx.test.espresso.assertion.ViewAssertions.matches
        import androidx.test.espresso.matcher.ViewMatchers.hasFocus
        import androidx.test.espresso.matcher.ViewMatchers.isDisplayed
        import androidx.test.espresso.matcher.ViewMatchers.isEnabled
        import androidx.test.espresso.matcher.ViewMatchers.isRoot
        import androidx.test.espresso.matcher.ViewMatchers.withContentDescription
        import androidx.test.espresso.matcher.ViewMatchers.withText
        import androidx.test.ext.junit.runners.AndroidJUnit4
        import androidx.test.platform.app.InstrumentationRegistry
        import androidx.test.espresso.util.HumanReadables
        import androidx.test.espresso.util.TreeIterables
        import org.hamcrest.Description
        import org.hamcrest.Matcher
        import org.hamcrest.Matchers.containsString
        import org.hamcrest.Matchers.anyOf
        import org.hamcrest.TypeSafeMatcher
        import org.junit.Test
        import org.junit.runner.RunWith
        import java.util.concurrent.TimeoutException\(contextImports.isEmpty ? "" : "\n\(contextImports)")

        /**
         * Generated by amoo from the Studio test "\(test.name)". Edit freely — this file has no
         * dependency on amoo or the companion apps once generated.
         */
        @RunWith(AndroidJUnit4::class)
        class \(className)\(baseClass) {
        \(needsResourceNameMatcher ? Self.resourceNameMatcherHelper + "\n" : "")
        \(Self.waitHelpers)

            @Test
            fun \(methodName)() {
                val targetContext = InstrumentationRegistry.getInstrumentation().targetContext
                val launchIntent = requireNotNull(
                    targetContext.packageManager.getLaunchIntentForPackage(targetContext.packageName)
                ) { "No launcher activity found for ${targetContext.packageName}" }
                launchIntent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TASK)

                ActivityScenario.launch<Activity>(launchIntent).use {
        \(launchedBody)
                }
            }
        }
        """
        return StudioTestExportResult(fileName: "\(className).kt", source: source)
    }

    private static let indent = "        "

    private static let resourceNameMatcherHelper: String = {
        let raw = """
        // Fallback for companion-reported resource names: generated code has no compile-time R.id
        // reference, so this matches on the runtime resource entry name. Recorded IDs also check
        // content descriptions because the companion uses those as IDs when available.
        private fun hasResourceEntryName(name: String): Matcher<View> {
            return object : TypeSafeMatcher<View>() {
                override fun describeTo(description: Description) {
                    description.appendText("with resource entry name: ").appendValue(name)
                }

                override fun matchesSafely(view: View): Boolean {
                    if (view.id == View.NO_ID) return false
                    return try {
                        view.resources.getResourceEntryName(view.id) == name
                    } catch (error: Exception) {
                        false
                    }
                }
            }
        }
        """
        return raw.split(separator: "\n", omittingEmptySubsequences: false)
            .map { $0.isEmpty ? "" : "    \($0)" }
            .joined(separator: "\n")
    }()

    private static let waitHelpers: String = {
        let raw = """
        private fun waitUntilDisplayed(matcher: Matcher<View>, timeoutMillis: Long): ViewAction =
            waitUntil(matcher, timeoutMillis, shouldBeDisplayed = true)

        private fun waitUntilNotDisplayed(matcher: Matcher<View>, timeoutMillis: Long): ViewAction =
            waitUntil(matcher, timeoutMillis, shouldBeDisplayed = false)

        private fun waitUntil(
            matcher: Matcher<View>,
            timeoutMillis: Long,
            shouldBeDisplayed: Boolean
        ): ViewAction {
            return object : ViewAction {
                override fun getConstraints(): Matcher<View> = isRoot()

                override fun getDescription(): String = if (shouldBeDisplayed) {
                    "wait up to ${timeoutMillis}ms for a displayed view matching $matcher"
                } else {
                    "wait up to ${timeoutMillis}ms for no displayed view matching $matcher"
                }

                override fun perform(uiController: UiController, root: View) {
                    val deadline = SystemClock.uptimeMillis() + timeoutMillis
                    do {
                        uiController.loopMainThreadUntilIdle()
                        val displayedMatchExists = TreeIterables.breadthFirstViewTraversal(root).any { view ->
                            matcher.matches(view) && isDisplayed().matches(view)
                        }
                        if (displayedMatchExists == shouldBeDisplayed) return
                        uiController.loopMainThreadForAtLeast(50)
                    } while (SystemClock.uptimeMillis() < deadline)

                    throw PerformException.Builder()
                        .withActionDescription(description)
                        .withViewDescription(HumanReadables.describe(root))
                        .withCause(TimeoutException(description))
                        .build()
                }
            }
        }
        """
        return raw.split(separator: "\n", omittingEmptySubsequences: false)
            .map { $0.isEmpty ? "" : "    \($0)" }
            .joined(separator: "\n")
    }()

    // A direct switch keeps the supported Studio-tool-to-Espresso mapping auditable in one place.
    // swiftlint:disable:next cyclomatic_complexity function_body_length
    private static func statement(for operation: StudioToolOperation, context: StudioTestContext?) throws -> String {
        if let helper = try TestHelperRendering.call(for: operation, context: context, literal: literal) {
            return "\(indent)\(helper)"
        }
        guard let tool = StudioTool(rawValue: operation.tool) else {
            throw TestCodeGeneratorError.unsupportedTool(operation.tool)
        }
        // No `default`: adding a StudioTool case must fail to compile here until it is handled.
        switch tool {
        case .tapElement:
            let target = try matcher(operation)
            return try """
            \(indent)onView(isRoot()).perform(waitUntilDisplayed(\(target), \(timeoutMilliseconds(for: operation))L))
            \(indent)onView(\(target)).perform(click())
            """

        case .setText:
            guard let value = operation.arguments["value"] else {
                throw TestCodeGeneratorError.missingArgument(tool: operation.tool, argument: "value")
            }
            let target = try matcher(operation)
            return try """
            \(indent)onView(isRoot()).perform(waitUntilDisplayed(\(target), \(timeoutMilliseconds(for: operation))L))
            \(indent)onView(\(target)).perform(replaceText(\(literal(value))))
            """

        case .typeText:
            guard let text = operation.arguments["text"] else {
                throw TestCodeGeneratorError.missingArgument(tool: operation.tool, argument: "text")
            }
            return try """
            \(indent)onView(isRoot()).perform(waitUntilDisplayed(hasFocus(), \(
                timeoutMilliseconds(for: operation)
            )L))
            \(indent)onView(hasFocus()).perform(replaceText(\(literal(text))))
            """

        case .swipeInDirection:
            let action = try "\(gesture(for: operation))()"
            let hasElement = operation.arguments["element_id"] != nil || operation.arguments["element_label"] != nil
            let target: String = if hasElement {
                try matcher(operation, idKey: "element_id", labelKey: "element_label")
            } else {
                "isDisplayed()"
            }
            guard hasElement else { return "\(indent)onView(isRoot()).perform(\(action))" }
            return try """
            \(indent)onView(isRoot()).perform(waitUntilDisplayed(\(target), \(timeoutMilliseconds(for: operation))L))
            \(indent)onView(\(target)).perform(\(action))
            """

        case .scroll:
            // GestureDirection inverts scroll for us — see its documentation for why.
            return try "\(indent)onView(isRoot()).perform(\(gesture(for: operation))())"

        case .waitForElement:
            let target = try matcher(operation)
            let timeout = try timeoutMilliseconds(for: operation)
            return "\(indent)onView(isRoot()).perform(waitUntilDisplayed(\(target), \(timeout)L))"

        case .assertVisible:
            let target = try matcher(operation)
            return try """
            \(indent)onView(isRoot()).perform(waitUntilDisplayed(\(target), \(timeoutMilliseconds(for: operation))L))
            \(indent)onView(\(target)).check(matches(isDisplayed()))
            """

        case .assertNotVisible:
            let target = try matcher(operation)
            let timeout = try timeoutMilliseconds(for: operation)
            return "\(indent)onView(isRoot()).perform(waitUntilNotDisplayed(\(target), \(timeout)L))"

        case .assertText:
            guard let expected = operation.arguments["value"] ?? operation.arguments["expected"] else {
                throw TestCodeGeneratorError.missingArgument(tool: operation.tool, argument: "value")
            }
            let target = try matcher(operation)
            return try """
            \(indent)onView(isRoot()).perform(waitUntilDisplayed(\(target), \(timeoutMilliseconds(for: operation))L))
            \(indent)onView(\(target)).check(matches(withText(\(literal(expected)))))
            """

        case .assertValue:
            guard let expected = operation.arguments["value"] ?? operation.arguments["expected"] else {
                throw TestCodeGeneratorError.missingArgument(tool: operation.tool, argument: "value")
            }
            let target = try matcher(operation)
            // On Android Views, the accessibility value represented by assert_value is exposed as
            // text. Compose has its own semantics-specific implementation below.
            return try """
            \(indent)onView(isRoot()).perform(waitUntilDisplayed(\(target), \(timeoutMilliseconds(for: operation))L))
            \(indent)onView(\(target)).check(matches(withText(\(literal(expected)))))
            """

        case .assertEnabled:
            let target = try matcher(operation)
            return try """
            \(indent)onView(isRoot()).perform(waitUntilDisplayed(\(target), \(timeoutMilliseconds(for: operation))L))
            \(indent)onView(\(target)).check(matches(isEnabled()))
            """

        case .takeScreenshot:
            return "\(indent)// take_screenshot: capture via androidx.test.runner.screenshot.Screenshot "
                + "in an instrumented test if needed"

        case .pressBack:
            return "\(indent)pressBack()"
        }
    }

    /// Espresso's `ViewActions` gesture name for this operation's direction.
    private static func gesture(for operation: StudioToolOperation) throws -> String {
        guard let raw = operation.arguments["direction"] else {
            throw TestCodeGeneratorError.missingArgument(tool: operation.tool, argument: "direction")
        }
        let direction = try GestureDirection.gestureDirection(for: operation.tool, rawDirection: raw)
        switch direction {
        case .up: return "swipeUp"
        case .down: return "swipeDown"
        case .left: return "swipeLeft"
        case .right: return "swipeRight"
        }
    }

    private static func matcher(
        _ operation: StudioToolOperation,
        idKey: String = "id",
        labelKey: String = "label",
        containsTextKey: String = "contains_text"
    ) throws -> String {
        if let id = operation.arguments[idKey] {
            return "anyOf(hasResourceEntryName(\(literal(id))), withContentDescription(\(literal(id))))"
        }
        if let label = operation.arguments[labelKey] {
            return "anyOf(withText(\(literal(label))), withContentDescription(\(literal(label))))"
        }
        if let contains = operation.arguments[containsTextKey] {
            return "anyOf(withText(containsString(\(literal(contains)))), "
                + "withContentDescription(containsString(\(literal(contains)))))"
        }
        throw TestCodeGeneratorError.missingArgument(tool: operation.tool, argument: "id, label, or contains_text")
    }

    private static func timeoutMilliseconds(for operation: StudioToolOperation) throws -> Int64 {
        guard let rawValue = operation.arguments["timeout_ms"] else { return 5000 }
        guard let milliseconds = Int64(rawValue), milliseconds > 0 else {
            throw TestCodeGeneratorError.invalidArgument(tool: operation.tool, argument: "timeout_ms", value: rawValue)
        }
        return milliseconds
    }

    private static func literal(_ value: String) -> String {
        var escaped = value
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
            .replacingOccurrences(of: "\n", with: "\\n")
            .replacingOccurrences(of: "\r", with: "\\r")
            .replacingOccurrences(of: "\t", with: "\\t")
        escaped = String(escaped.unicodeScalars.map { scalar -> String in
            guard scalar.value < 0x20 else { return String(scalar) }
            let hex = String(scalar.value, radix: 16)
            return "\\u\(String(repeating: "0", count: 4 - hex.count))\(hex)"
        }.joined())
        return "\"\(escaped)\""
    }
}
