import StudioProtocol

/// Emits a Kotlin Espresso instrumented test — no amoo companion app involved at run time.
///
/// Companion-normalized element `id`s are runtime resource names/content-descriptions as strings;
/// idiomatic Espresso (`withId(R.id.foo)`) needs a compile-time `R` reference this generator can't
/// resolve. Generated code falls back to a small `hasResourceEntryName` matcher instead of `R.id`,
/// with a comment pointing at the substitution — swap it for `withId(R.id...)` where convenient.
public struct EspressoEmitter: StudioCodeEmitting {
    public init() {}

    public func generate(_ test: StudioAuthoredTest) throws -> StudioTestExportResult {
        guard let operations = test.compiledPlan?.toolOperations, operations.isEmpty == false else {
            throw TestCodeGeneratorError.missingCompiledPlan
        }
        let pascalName = TestIdentifierNaming.pascalCase(test.name)
        let className = "\(pascalName)Test"
        let methodName = pascalName.prefix(1).lowercased() + pascalName.dropFirst()
        let body = try operations.map { try Self.statement(for: $0) }.joined(separator: "\n")
        let needsResourceNameMatcher = operations.contains {
            $0.arguments["id"] != nil && [
                "tap_element",
                "set_text",
                "wait_for_element",
                "assert_visible",
                "assert_not_visible",
                "assert_text"
            ].contains($0.tool)
        }

        let source = """
        import android.view.View
        import androidx.test.espresso.Espresso.onView
        import androidx.test.espresso.Espresso.pressBack
        import androidx.test.espresso.action.ViewActions.click
        import androidx.test.espresso.action.ViewActions.replaceText
        import androidx.test.espresso.action.ViewActions.swipeDown
        import androidx.test.espresso.action.ViewActions.swipeLeft
        import androidx.test.espresso.action.ViewActions.swipeRight
        import androidx.test.espresso.action.ViewActions.swipeUp
        import androidx.test.espresso.assertion.ViewAssertions.doesNotExist
        import androidx.test.espresso.assertion.ViewAssertions.matches
        import androidx.test.espresso.matcher.ViewMatchers.hasFocus
        import androidx.test.espresso.matcher.ViewMatchers.isDisplayed
        import androidx.test.espresso.matcher.ViewMatchers.withContentDescription
        import androidx.test.espresso.matcher.ViewMatchers.withText
        import androidx.test.ext.junit.runners.AndroidJUnit4
        import org.hamcrest.Description
        import org.hamcrest.Matcher
        import org.hamcrest.Matchers.containsString
        import org.hamcrest.TypeSafeMatcher
        import org.junit.Test
        import org.junit.runner.RunWith

        /**
         * Generated by amoo from the Studio test "\(test.name)". Edit freely — this file has no
         * dependency on amoo or the companion apps once generated.
         */
        @RunWith(AndroidJUnit4::class)
        class \(className) {
        \(needsResourceNameMatcher ? Self.resourceNameMatcherHelper + "\n" : "")
            @Test
            fun \(methodName)() {
        \(body)
            }
        }
        """
        return StudioTestExportResult(fileName: "\(className).kt", source: source)
    }

    private static let indent = "        "

    private static let resourceNameMatcherHelper: String = {
        let raw = """
        // Fallback for companion-reported element ids: generated code has no compile-time R.id
        // reference, so this matches on the runtime resource entry name instead. Swap a call site
        // for withId(R.id...) directly if you'd rather use the real resource id.
        private fun hasResourceEntryName(name: String): Matcher<View> {
            return object : TypeSafeMatcher<View>() {
                override fun describeTo(description: Description) {
                    description.appendText("with resource entry name: ").appendValue(name)
                }

                override fun matchesSafely(view: View): Boolean {
                    if (view.id == View.NO_ID) return false
                    return try {
                        view.resources.getResourceEntryName(view.id) == name
                    } catch (error: Exception) {
                        false
                    }
                }
            }
        }
        """
        return raw.split(separator: "\n", omittingEmptySubsequences: false)
            .map { $0.isEmpty ? "" : "    \($0)" }
            .joined(separator: "\n")
    }()

    private static func statement(for operation: StudioToolOperation) throws -> String {
        switch operation.tool {
        case "tap_element":
            return try "\(indent)onView(\(matcher(operation))).perform(click())"

        case "set_text":
            guard let value = operation.arguments["value"] else {
                throw TestCodeGeneratorError.missingArgument(tool: operation.tool, argument: "value")
            }
            return try "\(indent)onView(\(matcher(operation))).perform(replaceText(\(literal(value))))"

        case "type_text":
            guard let text = operation.arguments["text"] else {
                throw TestCodeGeneratorError.missingArgument(tool: operation.tool, argument: "text")
            }
            return "\(indent)onView(hasFocus()).perform(replaceText(\(literal(text)))) // TODO: types into the currently focused field — target the specific field with a matcher if known"

        case "swipe_in_direction":
            guard let direction = operation.arguments["direction"] else {
                throw TestCodeGeneratorError.missingArgument(tool: operation.tool, argument: "direction")
            }
            let action = switch direction.lowercased() {
            case "up": "swipeUp()"
            case "down": "swipeDown()"
            case "left": "swipeLeft()"
            case "right": "swipeRight()"
            default: "swipeUp()"
            }
            let hasElement = operation.arguments["element_id"] != nil || operation.arguments["element_label"] != nil
            let target = hasElement ? try matcher(operation, idKey: "element_id", labelKey: "element_label") : "isDisplayed()"
            return "\(indent)onView(\(target)).perform(\(action))"

        case "wait_for_element", "assert_visible":
            return try "\(indent)onView(\(matcher(operation))).check(matches(isDisplayed()))"

        case "assert_not_visible":
            return try "\(indent)onView(\(matcher(operation))).check(doesNotExist())"

        case "assert_text":
            guard let expected = operation.arguments["value"] ?? operation.arguments["expected"] else {
                throw TestCodeGeneratorError.missingArgument(tool: operation.tool, argument: "value")
            }
            return try "\(indent)onView(\(matcher(operation))).check(matches(withText(\(literal(expected)))))"

        case "take_screenshot":
            return "\(indent)// take_screenshot: capture via androidx.test.runner.screenshot.Screenshot in an instrumented test if needed"

        case "press_back":
            return "\(indent)pressBack()"

        default:
            throw TestCodeGeneratorError.unsupportedTool(operation.tool)
        }
    }

    private static func matcher(
        _ operation: StudioToolOperation,
        idKey: String = "id",
        labelKey: String = "label",
        containsTextKey: String = "contains_text"
    ) throws -> String {
        if let id = operation.arguments[idKey] {
            return "hasResourceEntryName(\(literal(id)))"
        }
        if let label = operation.arguments[labelKey] {
            return "withContentDescription(\(literal(label)))"
        }
        if let contains = operation.arguments[containsTextKey] {
            return "withText(containsString(\(literal(contains))))"
        }
        throw TestCodeGeneratorError.missingArgument(tool: operation.tool, argument: "id, label, or contains_text")
    }

    private static func literal(_ value: String) -> String {
        var escaped = value
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
            .replacingOccurrences(of: "\n", with: "\\n")
            .replacingOccurrences(of: "\r", with: "\\r")
            .replacingOccurrences(of: "\t", with: "\\t")
        escaped = String(escaped.unicodeScalars.map { scalar -> String in
            guard scalar.value < 0x20 else { return String(scalar) }
            let hex = String(scalar.value, radix: 16)
            return "\\u\(String(repeating: "0", count: 4 - hex.count))\(hex)"
        }.joined())
        return "\"\(escaped)\""
    }
}
