import StudioProtocol

/// Emits an XCTestCase driving `XCUIApplication` directly — no amoo companion app involved at run time.
public struct XCUITestEmitter: StudioCodeEmitting {
    public init() {}

    // SwiftLint measures the generated XCTest helper template as Swift function body lines.
    // swiftlint:disable:next function_body_length
    public func generate(_ test: StudioAuthoredTest) throws -> StudioTestExportResult {
        guard let operations = test.compiledPlan?.toolOperations, operations.isEmpty == false else {
            throw TestCodeGeneratorError.missingCompiledPlan
        }
        let className = "\(TestIdentifierNaming.pascalCase(test.name))Test"
        let methodName = "test\(TestIdentifierNaming.pascalCase(test.name))"
        let body = try operations.map { try Self.statement(for: $0) }.joined(separator: "\n")

        let source = """
        import XCTest

        /// Generated by amoo from the Studio test "\(test.name)". Edit freely — this file has no
        /// dependency on amoo or the companion apps once generated.
        final class \(className): XCTestCase {
            private let defaultTimeout: TimeInterval = 5

            private func waitForExistence(
                _ element: XCUIElement,
                timeout: TimeInterval? = nil,
                file: StaticString = #filePath,
                line: UInt = #line
            ) {
                XCTAssertTrue(
                    element.waitForExistence(timeout: timeout ?? defaultTimeout),
                    "Element did not exist before the timeout.\\n\\(element.debugDescription)",
                    file: file,
                    line: line
                )
            }

            private func waitForHittability(
                _ element: XCUIElement,
                timeout: TimeInterval? = nil,
                file: StaticString = #filePath,
                line: UInt = #line
            ) {
                XCTAssertTrue(
                    element.wait(for: \\.isHittable, toEqual: true, timeout: timeout ?? defaultTimeout),
                    "Element was not visible and hittable before the timeout.\\n\\(element.debugDescription)",
                    file: file,
                    line: line
                )
            }

            private func waitForNonHittability(
                _ element: XCUIElement,
                timeout: TimeInterval? = nil,
                file: StaticString = #filePath,
                line: UInt = #line
            ) {
                XCTAssertTrue(
                    element.wait(for: \\.isHittable, toEqual: false, timeout: timeout ?? defaultTimeout),
                    "Element was still visible and hittable after the timeout.\\n\\(element.debugDescription)",
                    file: file,
                    line: line
                )
            }

            func \(methodName)() throws {
                let app = XCUIApplication()
                app.launch()

        \(body)
            }
        }
        """
        return StudioTestExportResult(fileName: "\(className).swift", source: source)
    }

    private static let indent = "        "

    // A direct switch keeps the supported Studio-tool-to-XCUITest mapping auditable in one place.
    // swiftlint:disable:next cyclomatic_complexity function_body_length
    private static func statement(for operation: StudioToolOperation) throws -> String {
        switch operation.tool {
        case "tap_element":
            let element = try query(operation)
            let variable = "element_\(safeSuffix(operation.id))"
            return try """
            \(indent)let \(variable) = \(element)
            \(indent)waitForHittability(\(variable), timeout: \(timeoutSeconds(for: operation)))
            \(indent)\(variable).tap()
            """

        case "set_text":
            guard let value = operation.arguments["value"] else {
                throw TestCodeGeneratorError.missingArgument(tool: operation.tool, argument: "value")
            }
            let element = try query(operation)
            let variable = "element_\(safeSuffix(operation.id))"
            return try """
            \(indent)let \(variable) = \(element)
            \(indent)waitForHittability(\(variable), timeout: \(timeoutSeconds(for: operation)))
            \(indent)\(variable).tap()
            \(indent)\(variable).typeText(\(literal(value)))
            """

        case "type_text":
            guard let text = operation.arguments["text"] else {
                throw TestCodeGeneratorError.missingArgument(tool: operation.tool, argument: "text")
            }
            return "\(indent)app.typeText(\(literal(text)))"

        case "swipe_in_direction":
            guard let direction = operation.arguments["direction"] else {
                throw TestCodeGeneratorError.missingArgument(tool: operation.tool, argument: "direction")
            }
            let target = operation.arguments["element_id"] != nil || operation.arguments["element_label"] != nil
                ? try query(operation, idKey: "element_id", labelKey: "element_label")
                : "app"
            let gesture = switch direction.lowercased() {
            case "up": "swipeUp"
            case "down": "swipeDown"
            case "left": "swipeLeft"
            case "right": "swipeRight"
            default: "swipeUp"
            }
            if target == "app" {
                return "\(indent)app.\(gesture)()"
            }
            let variable = "element_\(safeSuffix(operation.id))"
            return try """
            \(indent)let \(variable) = \(target)
            \(indent)waitForHittability(\(variable), timeout: \(timeoutSeconds(for: operation)))
            \(indent)\(variable).\(gesture)()
            """

        case "wait_for_element", "assert_visible":
            return try waitStatement(for: operation, exists: true)

        case "assert_not_visible":
            return try waitStatement(for: operation, exists: false)

        case "assert_text":
            guard let expected = operation.arguments["value"] ?? operation.arguments["expected"] else {
                throw TestCodeGeneratorError.missingArgument(tool: operation.tool, argument: "value")
            }
            let variable = "element_\(safeSuffix(operation.id))"
            return try """
            \(indent)let \(variable) = \(query(operation))
            \(indent)waitForExistence(\(variable), timeout: \(timeoutSeconds(for: operation)))
            \(indent)XCTAssertEqual(\(variable).label, \(literal(expected)))
            """

        case "take_screenshot":
            return """
            \(indent)let screenshot_\(safeSuffix(operation.id)) = XCTAttachment(screenshot: app.screenshot())
            \(indent)screenshot_\(safeSuffix(operation.id)).lifetime = .keepAlways
            \(indent)add(screenshot_\(safeSuffix(operation.id)))
            """

        case "press_back":
            // iOS has no system "back" API from XCUITest — this is a best-effort edge-swipe gesture.
            // Adjust to your app's own back control (e.g. a navigation bar back button) if this doesn't match.
            return "\(indent)app.swipeRight() // press_back: best-effort edge-swipe back gesture"

        default:
            throw TestCodeGeneratorError.unsupportedTool(operation.tool)
        }
    }

    private static func waitStatement(for operation: StudioToolOperation, exists: Bool) throws -> String {
        let element = try query(operation)
        let suffix = safeSuffix(operation.id)
        let helper = exists ? (operation.tool == "assert_visible" ? "waitForHittability" : "waitForExistence")
            : "waitForNonHittability"
        return try """
        \(indent)let element_\(suffix) = \(element)
        \(indent)\(helper)(element_\(suffix), timeout: \(timeoutSeconds(for: operation)))
        """
    }

    private static func timeoutSeconds(for operation: StudioToolOperation) throws -> Double {
        guard let rawValue = operation.arguments["timeout_ms"] else { return 5 }
        guard let milliseconds = Int64(rawValue), milliseconds > 0 else {
            throw TestCodeGeneratorError.invalidArgument(tool: operation.tool, argument: "timeout_ms", value: rawValue)
        }
        return Double(milliseconds) / 1000
    }

    private static func query(
        _ operation: StudioToolOperation,
        idKey: String = "id",
        labelKey: String = "label",
        containsTextKey: String = "contains_text"
    ) throws -> String {
        if let id = operation.arguments[idKey] {
            return "app.descendants(matching: .any)[\(literal(id))]"
        }
        if let label = operation.arguments[labelKey] {
            return "app.descendants(matching: .any)"
                + ".matching(NSPredicate(format: \"label == %@\", \(literal(label)))).firstMatch"
        }
        if let contains = operation.arguments[containsTextKey] {
            return "app.descendants(matching: .any)"
                + ".matching(NSPredicate(format: \"label CONTAINS %@\", \(literal(contains)))).firstMatch"
        }
        throw TestCodeGeneratorError.missingArgument(tool: operation.tool, argument: "id, label, or contains_text")
    }

    private static func literal(_ value: String) -> String {
        var escaped = value
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
            .replacingOccurrences(of: "\n", with: "\\n")
            .replacingOccurrences(of: "\r", with: "\\r")
            .replacingOccurrences(of: "\t", with: "\\t")
        escaped = String(escaped.unicodeScalars.map { scalar -> String in
            guard scalar.value < 0x20 else { return String(scalar) }
            return "\\u{\(String(scalar.value, radix: 16))}"
        }.joined())
        return "\"\(escaped)\""
    }

    private static func safeSuffix(_ id: String) -> String {
        String(id.map { $0.isLetter || $0.isNumber ? $0 : "_" })
    }
}
