import StudioProtocol

// Emits an XCTestCase driving `XCUIApplication` directly — no amoo companion app involved at run time.
// swiftlint:disable:next type_body_length
public struct XCUITestEmitter: StudioCodeEmitting {
    public init() {}

    // SwiftLint measures the generated XCTest helper template as Swift function body lines.
    // swiftlint:disable:next function_body_length
    public func generate(_ test: StudioAuthoredTest) throws -> StudioTestExportResult {
        guard let operations = test.compiledPlan?.toolOperations, operations.isEmpty == false else {
            throw TestCodeGeneratorError.missingCompiledPlan
        }
        let className = "\(TestIdentifierNaming.pascalCase(test.name))Test"
        let methodName = "test\(TestIdentifierNaming.pascalCase(test.name))"
        var localNames = LocalNameAllocator()
        var lookups = [String: String]()
        let body = try operations.map {
            try Self.statement(for: $0, context: test.testContext, localNames: &localNames, lookups: &lookups)
        }.joined(separator: "\n")
        let contextImports = TestHelperRendering.imports(for: test.testContext)
            .map { "import \($0)" }
            .joined(separator: "\n")
        // The emitter launches unless the context declares that the harness already does. Naming a
        // base class is not that declaration — see `StudioTestContext.harnessLaunchesApp`. The
        // overrides chain to super either way, or a supplied base class's own setUp never runs.
        let baseClass = test.testContext?.baseClass ?? "XCTestCase"
        let appFactory = test.testContext?.appFactory ?? "XCUIApplication()"
        let launch = test.testContext?.harnessLaunchesApp == true ? "" : "\n        app.launch()"

        let source = """
        import XCTest\(contextImports.isEmpty ? "" : "\n\(contextImports)")

        /// Generated by amoo from the Studio test "\(test.name)". Edit freely — this file has no
        /// dependency on amoo or the companion apps once generated.
        final class \(className): \(baseClass) {
            private let defaultTimeout: TimeInterval = 5
            private lazy var app = \(appFactory)

            override func setUpWithError() throws {
                try super.setUpWithError()
                continueAfterFailure = false\(launch)
            }

            override func tearDownWithError() throws {
                if testRun?.failureCount ?? 0 > 0 {
                    let screenshot = XCTAttachment(screenshot: app.screenshot())
                    screenshot.name = "Failure screenshot"
                    screenshot.lifetime = .keepAlways
                    add(screenshot)

                    let hierarchy = XCTAttachment(string: app.debugDescription)
                    hierarchy.name = "Failure UI hierarchy"
                    hierarchy.lifetime = .keepAlways
                    add(hierarchy)
                }
                try super.tearDownWithError()
            }

            private func waitForExistence(
                _ element: XCUIElement,
                named name: String = "Element",
                timeout: TimeInterval? = nil,
                file: StaticString = #filePath,
                line: UInt = #line
            ) {
                XCTAssertTrue(
                    element.waitForExistence(timeout: timeout ?? defaultTimeout),
                    "\\(name) did not exist before the timeout.\\n\\(element.debugDescription)",
                    file: file,
                    line: line
                )
            }

            private func waitForHittability(
                _ element: XCUIElement,
                named name: String = "Element",
                timeout: TimeInterval? = nil,
                file: StaticString = #filePath,
                line: UInt = #line
            ) {
                XCTAssertTrue(
                    element.wait(for: \\.isHittable, toEqual: true, timeout: timeout ?? defaultTimeout),
                    "\\(name) was not visible and hittable before the timeout.\\n\\(element.debugDescription)",
                    file: file,
                    line: line
                )
            }

            private func waitForAbsence(
                _ element: XCUIElement,
                named name: String = "Element",
                timeout: TimeInterval? = nil,
                file: StaticString = #filePath,
                line: UInt = #line
            ) {
                XCTAssertTrue(
                    element.wait(for: \\.exists, toEqual: false, timeout: timeout ?? defaultTimeout),
                    "\\(name) still existed after the timeout.\\n\\(element.debugDescription)",
                    file: file,
                    line: line
                )
            }

            private func replaceText(in element: XCUIElement, with text: String) {
                element.tap()
                if let currentValue = element.value as? String, !currentValue.isEmpty {
                    element.typeText(String(repeating: XCUIKeyboardKey.delete.rawValue, count: currentValue.count))
                }
                if !text.isEmpty {
                    element.typeText(text)
                }
            }

            private func pressBack() {
                let backButton = app.navigationBars.buttons.element(boundBy: 0)
                if backButton.exists, backButton.isHittable {
                    backButton.tap()
                } else {
                    app.swipeRight()
                }
            }

            func \(methodName)() throws {
        \(body)
            }
        }
        """
        return StudioTestExportResult(fileName: "\(className).swift", source: source + "\n")
    }

    private static let indent = "        "

    // A direct switch keeps the supported Studio-tool-to-XCUITest mapping auditable in one place.
    // swiftlint:disable:next cyclomatic_complexity function_body_length
    private static func statement(
        for operation: StudioToolOperation,
        context: StudioTestContext?,
        localNames: inout LocalNameAllocator,
        lookups: inout [String: String]
    ) throws -> String {
        if let helper = try TestHelperRendering.call(for: operation, context: context, literal: literal) {
            return "\(indent)\(helper)"
        }
        guard let tool = StudioTool(rawValue: operation.tool) else {
            throw TestCodeGeneratorError.unsupportedTool(operation.tool)
        }
        // No `default`: adding a StudioTool case must fail to compile here until it is handled.
        switch tool {
        case .tapElement:
            let (_, variable, declaration) = try lookup(
                operation, context: context, localNames: &localNames, lookups: &lookups
            )
            return try """
            \(declaration)
            \(indent)\(waitCall("waitForHittability", variable, operation))
            \(indent)\(variable).tap()
            """

        case .setText:
            guard let value = operation.arguments["value"] else {
                throw TestCodeGeneratorError.missingArgument(tool: operation.tool, argument: "value")
            }
            let (_, variable, declaration) = try lookup(
                operation, context: context, localNames: &localNames, lookups: &lookups
            )
            return try """
            \(declaration)
            \(indent)\(waitCall("waitForHittability", variable, operation))
            \(indent)replaceText(in: \(variable), with: \(literal(value)))
            """

        case .typeText:
            guard let text = operation.arguments["text"] else {
                throw TestCodeGeneratorError.missingArgument(tool: operation.tool, argument: "text")
            }
            return "\(indent)app.typeText(\(literal(text)))"

        case .swipeInDirection:
            let target = operation.arguments["element_id"] != nil || operation.arguments["element_label"] != nil
                ? try query(operation, idKey: "element_id", labelKey: "element_label")
                : "app"
            let gesture = try gesture(for: operation)
            if target == "app" {
                return "\(indent)app.\(gesture)()"
            }
            let variable = localNames.next(elementVariableName(
                for: operation,
                idKey: "element_id",
                labelKey: "element_label"
            ))
            return try """
            \(indent)let \(variable) = \(target)
            \(indent)\(waitCall("waitForHittability", variable, operation))
            \(indent)\(variable).\(gesture)()
            """

        case .scroll:
            // GestureDirection inverts scroll for us — see its documentation for why.
            return try "\(indent)app.\(gesture(for: operation))()"

        case .waitForElement, .assertVisible:
            return try waitStatement(
                for: operation,
                exists: true,
                context: context,
                localNames: &localNames,
                lookups: &lookups
            )

        case .assertNotVisible:
            return try waitStatement(
                for: operation,
                exists: false,
                context: context,
                localNames: &localNames,
                lookups: &lookups
            )

        case .assertEnabled:
            let (_, variable, declaration) = try lookup(
                operation, context: context, localNames: &localNames, lookups: &lookups
            )
            return try """
            \(declaration)
            \(indent)\(waitCall("waitForExistence", variable, operation))
            \(indent)XCTAssertTrue(\(variable).isEnabled)
            """

        case .assertText:
            guard let expected = operation.arguments["value"] ?? operation.arguments["expected"] else {
                throw TestCodeGeneratorError.missingArgument(tool: operation.tool, argument: "value")
            }
            let (_, variable, declaration) = try lookup(
                operation, context: context, localNames: &localNames, lookups: &lookups
            )
            return try """
            \(declaration)
            \(indent)\(waitCall("waitForExistence", variable, operation))
            \(indent)XCTAssertEqual(\(variable).label, \(literal(expected)))
            """

        case .assertValue:
            guard let expected = operation.arguments["value"] ?? operation.arguments["expected"] else {
                throw TestCodeGeneratorError.missingArgument(tool: operation.tool, argument: "value")
            }
            let (_, variable, declaration) = try lookup(
                operation, context: context, localNames: &localNames, lookups: &lookups
            )
            return try """
            \(declaration)
            \(indent)\(waitCall("waitForExistence", variable, operation))
            \(indent)XCTAssertEqual(\(variable).value as? String, \(literal(expected)))
            """

        case .takeScreenshot:
            let variable = localNames.next("screenshot")
            return """
            \(indent)let \(variable) = XCTAttachment(screenshot: app.screenshot())
            \(indent)\(variable).lifetime = .keepAlways
            \(indent)add(\(variable))
            """

        case .pressBack:
            return "\(indent)pressBack()"
        }
    }

    private static func waitStatement(
        for operation: StudioToolOperation,
        exists: Bool,
        context: StudioTestContext?,
        localNames: inout LocalNameAllocator,
        lookups: inout [String: String]
    ) throws -> String {
        let (_, variable, declaration) = try lookup(
            operation, context: context, localNames: &localNames, lookups: &lookups
        )
        let helper = exists ? (operation.tool == "assert_visible" ? "waitForHittability" : "waitForExistence")
            : "waitForAbsence"
        // The wait already asserts, and `continueAfterFailure = false` stops the test there, so a
        // trailing XCTAssert would be unreachable. Name the element in the wait instead — that is
        // what makes the failure readable.
        return try """
        \(declaration)
        \(indent)\(waitCall(helper, variable, operation))
        """
    }

    /// One call to a generated wait helper. `named:` carries the local variable's name so a
    /// timeout failure says which element it was waiting on.
    private static func waitCall(
        _ helper: String,
        _ variable: String,
        _ operation: StudioToolOperation
    ) throws -> String {
        try "\(helper)(\(variable), named: \(literal(variable)), timeout: \(timeoutSeconds(for: operation)))"
    }

    private static func elementVariableName(
        for operation: StudioToolOperation,
        idKey: String = "id",
        labelKey: String = "label",
        containsTextKey: String = "contains_text"
    ) -> String {
        TestIdentifierNaming.elementVariableBase(
            id: operation.arguments[idKey],
            label: operation.arguments[labelKey],
            containsText: operation.arguments[containsTextKey]
        )
    }

    /// XCUITest's gesture method name for this operation's direction.
    private static func gesture(for operation: StudioToolOperation) throws -> String {
        guard let raw = operation.arguments["direction"] else {
            throw TestCodeGeneratorError.missingArgument(tool: operation.tool, argument: "direction")
        }
        let direction = try GestureDirection.gestureDirection(for: operation.tool, rawDirection: raw)
        switch direction {
        case .up: return "swipeUp"
        case .down: return "swipeDown"
        case .left: return "swipeLeft"
        case .right: return "swipeRight"
        }
    }

    private static func timeoutSeconds(for operation: StudioToolOperation) throws -> Double {
        guard let rawValue = operation.arguments["timeout_ms"] else { return 5 }
        guard let milliseconds = Int64(rawValue), milliseconds > 0 else {
            throw TestCodeGeneratorError.invalidArgument(tool: operation.tool, argument: "timeout_ms", value: rawValue)
        }
        return Double(milliseconds) / 1000
    }

    // Named components make this tuple an internal rendering detail, never an API value.
    // swiftlint:disable large_tuple
    private static func lookup(
        _ operation: StudioToolOperation,
        context: StudioTestContext?,
        localNames: inout LocalNameAllocator,
        lookups: inout [String: String]
    ) throws -> (element: String, variable: String, declaration: String) {
        let element = try query(operation, context: context)
        if let variable = lookups[element] {
            return (element, variable, "")
        }
        let mappedID = operation.arguments["id"].flatMap { context?.selectorExpressions[$0] }
        let base = mappedID.map { TestIdentifierNaming.elementVariableBase(id: $0) }
            ?? elementVariableName(for: operation)
        let variable = localNames.next(base)
        lookups[element] = variable
        return (element, variable, "\(indent)let \(variable) = \(element)")
    }

    // swiftlint:enable large_tuple

    private static func query(
        _ operation: StudioToolOperation,
        context: StudioTestContext? = nil,
        idKey: String = "id",
        labelKey: String = "label",
        containsTextKey: String = "contains_text"
    ) throws -> String {
        if let id = operation.arguments[idKey] {
            if let mapped = context?.selectorExpressions[id] {
                let template = context?.idLookupTemplate ?? "app.descendants(matching: .any)[{{id}}]"
                return template.replacingOccurrences(of: "{{id}}", with: mapped)
            }
            return "app.descendants(matching: .any)[\(literal(id))]"
        }
        if let label = operation.arguments[labelKey] {
            return "app.descendants(matching: .any)"
                + ".matching(NSPredicate(format: \"label == %@\", \(literal(label)))).firstMatch"
        }
        if let contains = operation.arguments[containsTextKey] {
            return "app.descendants(matching: .any)"
                + ".matching(NSPredicate(format: \"label CONTAINS %@\", \(literal(contains)))).firstMatch"
        }
        throw TestCodeGeneratorError.missingArgument(tool: operation.tool, argument: "id, label, or contains_text")
    }

    private static func literal(_ value: String) -> String {
        var escaped = value
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
            .replacingOccurrences(of: "\n", with: "\\n")
            .replacingOccurrences(of: "\r", with: "\\r")
            .replacingOccurrences(of: "\t", with: "\\t")
        escaped = String(escaped.unicodeScalars.map { scalar -> String in
            guard scalar.value < 0x20 else { return String(scalar) }
            return "\\u{\(String(scalar.value, radix: 16))}"
        }.joined())
        return "\"\(escaped)\""
    }
}
