import android.app.Activity
import android.content.Intent
import androidx.compose.ui.test.assertIsDisplayed
import androidx.compose.ui.test.assertIsEnabled
import androidx.compose.ui.test.assertIsNotDisplayed
import androidx.compose.ui.test.assertTextEquals
import androidx.compose.ui.test.hasContentDescription
import androidx.compose.ui.test.hasTestTag
import androidx.compose.ui.test.hasText
import androidx.compose.ui.test.isFocused
import androidx.compose.ui.test.junit4.v2.createEmptyComposeRule
import androidx.compose.ui.test.onRoot
import androidx.compose.ui.test.performClick
import androidx.compose.ui.test.performTextInput
import androidx.compose.ui.test.performTextReplacement
import androidx.compose.ui.test.performTouchInput
import androidx.compose.ui.test.swipeDown
import androidx.compose.ui.test.swipeLeft
import androidx.compose.ui.test.swipeRight
import androidx.compose.ui.test.swipeUp
import androidx.test.core.app.ActivityScenario
import androidx.test.espresso.Espresso.pressBack
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith

/**
 * Generated by amoo from the Studio test "Compose Fixture Flow". Edit freely — this file has no
 * dependency on amoo or the companion apps once generated.
 */
@RunWith(AndroidJUnit4::class)
class ComposeFixtureFlowTest {
    @get:Rule
    val composeTestRule = createEmptyComposeRule()

    @Test
    fun testComposeFixtureFlow() {
        val targetContext = InstrumentationRegistry.getInstrumentation().targetContext
        val launchIntent = requireNotNull(
            targetContext.packageManager.getLaunchIntentForPackage(targetContext.packageName)
        ) { "No launcher activity found for ${targetContext.packageName}" }
        launchIntent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TASK)

        ActivityScenario.launch<Activity>(launchIntent).use {
            composeTestRule.onNode(hasTestTag("fixture_home_title")).assertIsDisplayed()
            composeTestRule.onNode(hasTestTag("fixture_home_title")).assertTextEquals("Compose Fixture Home")
            composeTestRule.onNode(hasTestTag("fixture_open_details")).assertIsEnabled()
            composeTestRule.onNode(hasTestTag("fixture_open_details")).assertIsDisplayed().performClick()
            composeTestRule.onNode(hasTestTag("fixture_detail_row_0")).assertIsDisplayed()
        }
    }
}