#!/bin/sh
# This file is generated at build time, never from the checkout at MCP startup.
set -eu
repo=$1
out=$2
mkdir -p "$out"
commit=unknown
fingerprint=unknown
dirty=unknown
if git -C "$repo" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    commit=$(git -C "$repo" rev-parse HEAD)
    dirty=false
    if [ -n "$(git -C "$repo" status --porcelain -- Sources Protos Package.swift Package.resolved BuildPlugins scripts/build-provenance.sh)" ]; then
        dirty=true
    fi
    fingerprint=$(
        git -C "$repo" ls-files -co --exclude-standard -- Sources Protos Package.swift Package.resolved BuildPlugins scripts/build-provenance.sh |
        sort -u |
        while IFS= read -r path; do
            [ -f "$repo/$path" ] || continue
            printf '%s\n' "$path"
            git -C "$repo" hash-object -- "$path"
        done | git -C "$repo" hash-object --stdin
    )
fi
temp="$out/CompiledBuildProvenance.swift.tmp"
cat > "$temp" <<EOF
// Generated by BuildProvenancePlugin. Do not edit.
enum CompiledBuildProvenance {
    static let commit = "$commit"
    static let sourceFingerprint = "$fingerprint"
    static let dirty = "$dirty"
}
EOF
if ! cmp -s "$temp" "$out/CompiledBuildProvenance.swift"; then
    mv "$temp" "$out/CompiledBuildProvenance.swift"
else
    rm "$temp"
fi
