// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: accessibility.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

/// If the compiler emits an error on this type, it is because this file
/// was generated by a version of the `protoc` Swift plug-in that is
/// incompatible with the version of SwiftProtobuf to which you are linking.
/// Please ensure that you are building against the same version of the API
/// that was used to generate this file.
private struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
    struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
    typealias Version = _2
}

public struct MobileTesting_ViewHierarchyRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var appID: String = .init()

    /// If app_id is empty, the companion checks each candidate bundle ID using
    /// XCUIApplication.state == .runningForeground and returns the first match.
    public var candidateBundleIds: [String] = []

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct MobileTesting_ViewHierarchyResponse: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var root: MobileTesting_ViewNode {
        get { _root ?? MobileTesting_ViewNode() }
        set { _root = newValue }
    }

    /// Returns true if `root` has been explicitly set.
    public var hasRoot: Bool {
        _root != nil
    }

    /// Clears the value of `root`. Subsequent reads from it will return its default value.
    public mutating func clearRoot() {
        _root = nil
    }

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _root: MobileTesting_ViewNode?
}

public struct MobileTesting_FindElementsRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var selector: MobileTesting_ElementSelector {
        get { _selector ?? MobileTesting_ElementSelector() }
        set { _selector = newValue }
    }

    /// Returns true if `selector` has been explicitly set.
    public var hasSelector: Bool {
        _selector != nil
    }

    /// Clears the value of `selector`. Subsequent reads from it will return its default value.
    public mutating func clearSelector() {
        _selector = nil
    }

    public var appID: String = .init()

    public var candidateBundleIds: [String] = []

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _selector: MobileTesting_ElementSelector?
}

public struct MobileTesting_FindElementsResponse: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var elements: [MobileTesting_ElementInfo] = []

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct MobileTesting_WaitForElementRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var selector: MobileTesting_ElementSelector {
        get { _selector ?? MobileTesting_ElementSelector() }
        set { _selector = newValue }
    }

    /// Returns true if `selector` has been explicitly set.
    public var hasSelector: Bool {
        _selector != nil
    }

    /// Clears the value of `selector`. Subsequent reads from it will return its default value.
    public mutating func clearSelector() {
        _selector = nil
    }

    public var timeout: MobileTesting_Duration {
        get { _timeout ?? MobileTesting_Duration() }
        set { _timeout = newValue }
    }

    /// Returns true if `timeout` has been explicitly set.
    public var hasTimeout: Bool {
        _timeout != nil
    }

    /// Clears the value of `timeout`. Subsequent reads from it will return its default value.
    public mutating func clearTimeout() {
        _timeout = nil
    }

    public var appID: String = .init()

    public var candidateBundleIds: [String] = []

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _selector: MobileTesting_ElementSelector?
    fileprivate var _timeout: MobileTesting_Duration?
}

public struct MobileTesting_WaitForElementResponse: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var found: Bool = false

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

private let _protobuf_package = "mobile.testing.v1"

extension MobileTesting_ViewHierarchyRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding
{
    public static let protoMessageName: String = _protobuf_package + ".ViewHierarchyRequest"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}app_id\0\u{3}candidate_bundle_ids\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularStringField(value: &appID)
            case 2: try decoder.decodeRepeatedStringField(value: &candidateBundleIds)
            default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !appID.isEmpty {
            try visitor.visitSingularStringField(value: appID, fieldNumber: 1)
        }
        if !candidateBundleIds.isEmpty {
            try visitor.visitRepeatedStringField(value: candidateBundleIds, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: MobileTesting_ViewHierarchyRequest, rhs: MobileTesting_ViewHierarchyRequest) -> Bool {
        if lhs.appID != rhs.appID { return false }
        if lhs.candidateBundleIds != rhs.candidateBundleIds { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension MobileTesting_ViewHierarchyResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding
{
    public static let protoMessageName: String = _protobuf_package + ".ViewHierarchyResponse"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}root\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularMessageField(value: &_root)
            default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        if let v = _root {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: MobileTesting_ViewHierarchyResponse, rhs: MobileTesting_ViewHierarchyResponse) -> Bool {
        if lhs._root != rhs._root { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension MobileTesting_FindElementsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding
{
    public static let protoMessageName: String = _protobuf_package + ".FindElementsRequest"
    public static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(bytecode: "\0\u{1}selector\0\u{3}app_id\0\u{3}candidate_bundle_ids\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularMessageField(value: &_selector)
            case 2: try decoder.decodeSingularStringField(value: &appID)
            case 3: try decoder.decodeRepeatedStringField(value: &candidateBundleIds)
            default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        if let v = _selector {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
        }
        if !appID.isEmpty {
            try visitor.visitSingularStringField(value: appID, fieldNumber: 2)
        }
        if !candidateBundleIds.isEmpty {
            try visitor.visitRepeatedStringField(value: candidateBundleIds, fieldNumber: 3)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: MobileTesting_FindElementsRequest, rhs: MobileTesting_FindElementsRequest) -> Bool {
        if lhs._selector != rhs._selector { return false }
        if lhs.appID != rhs.appID { return false }
        if lhs.candidateBundleIds != rhs.candidateBundleIds { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension MobileTesting_FindElementsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding
{
    public static let protoMessageName: String = _protobuf_package + ".FindElementsResponse"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}elements\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeRepeatedMessageField(value: &elements)
            default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !elements.isEmpty {
            try visitor.visitRepeatedMessageField(value: elements, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: MobileTesting_FindElementsResponse, rhs: MobileTesting_FindElementsResponse) -> Bool {
        if lhs.elements != rhs.elements { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension MobileTesting_WaitForElementRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding
{
    public static let protoMessageName: String = _protobuf_package + ".WaitForElementRequest"
    public static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(bytecode: "\0\u{1}selector\0\u{1}timeout\0\u{3}app_id\0\u{3}candidate_bundle_ids\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularMessageField(value: &_selector)
            case 2: try decoder.decodeSingularMessageField(value: &_timeout)
            case 3: try decoder.decodeSingularStringField(value: &appID)
            case 4: try decoder.decodeRepeatedStringField(value: &candidateBundleIds)
            default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        if let v = _selector {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
        }
        try { if let v = self._timeout {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
        } }()
        if !appID.isEmpty {
            try visitor.visitSingularStringField(value: appID, fieldNumber: 3)
        }
        if !candidateBundleIds.isEmpty {
            try visitor.visitRepeatedStringField(value: candidateBundleIds, fieldNumber: 4)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: MobileTesting_WaitForElementRequest, rhs: MobileTesting_WaitForElementRequest) -> Bool {
        if lhs._selector != rhs._selector { return false }
        if lhs._timeout != rhs._timeout { return false }
        if lhs.appID != rhs.appID { return false }
        if lhs.candidateBundleIds != rhs.candidateBundleIds { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension MobileTesting_WaitForElementResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding
{
    public static let protoMessageName: String = _protobuf_package + ".WaitForElementResponse"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}found\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularBoolField(value: &found)
            default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if found != false {
            try visitor.visitSingularBoolField(value: found, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (
        lhs: MobileTesting_WaitForElementResponse,
        rhs: MobileTesting_WaitForElementResponse
    ) -> Bool {
        if lhs.found != rhs.found { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}
