// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: actions.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

/// If the compiler emits an error on this type, it is because this file
/// was generated by a version of the `protoc` Swift plug-in that is
/// incompatible with the version of SwiftProtobuf to which you are linking.
/// Please ensure that you are building against the same version of the API
/// that was used to generate this file.
private struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
    struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
    typealias Version = _2
}

public struct MobileTesting_StartSessionRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var requestedSessionID: String = .init()

    public var appID: String = .init()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct MobileTesting_StartSessionResponse: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var sessionID: String = .init()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct MobileTesting_CapabilitiesRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct MobileTesting_CapabilitiesResponse: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var capabilities: [MobileTesting_CapabilityDescriptor] = []

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct MobileTesting_EndSessionRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var sessionID: String = .init()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct MobileTesting_EndSessionResponse: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var ended: Bool = false

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct MobileTesting_TapRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var point: MobileTesting_Point {
        get { _point ?? MobileTesting_Point() }
        set { _point = newValue }
    }

    /// Returns true if `point` has been explicitly set.
    public var hasPoint: Bool {
        _point != nil
    }

    /// Clears the value of `point`. Subsequent reads from it will return its default value.
    public mutating func clearPoint() {
        _point = nil
    }

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _point: MobileTesting_Point?
}

public struct MobileTesting_LongPressRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var point: MobileTesting_Point {
        get { _point ?? MobileTesting_Point() }
        set { _point = newValue }
    }

    /// Returns true if `point` has been explicitly set.
    public var hasPoint: Bool {
        _point != nil
    }

    /// Clears the value of `point`. Subsequent reads from it will return its default value.
    public mutating func clearPoint() {
        _point = nil
    }

    public var duration: MobileTesting_Duration {
        get { _duration ?? MobileTesting_Duration() }
        set { _duration = newValue }
    }

    /// Returns true if `duration` has been explicitly set.
    public var hasDuration: Bool {
        _duration != nil
    }

    /// Clears the value of `duration`. Subsequent reads from it will return its default value.
    public mutating func clearDuration() {
        _duration = nil
    }

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _point: MobileTesting_Point?
    fileprivate var _duration: MobileTesting_Duration?
}

public struct MobileTesting_TapElementRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var selector: MobileTesting_ElementSelector {
        get { _selector ?? MobileTesting_ElementSelector() }
        set { _selector = newValue }
    }

    /// Returns true if `selector` has been explicitly set.
    public var hasSelector: Bool {
        _selector != nil
    }

    /// Clears the value of `selector`. Subsequent reads from it will return its default value.
    public mutating func clearSelector() {
        _selector = nil
    }

    public var appID: String = .init()

    public var candidateBundleIds: [String] = []

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _selector: MobileTesting_ElementSelector?
}

public struct MobileTesting_SwipeRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var from: MobileTesting_Point {
        get { _from ?? MobileTesting_Point() }
        set { _from = newValue }
    }

    /// Returns true if `from` has been explicitly set.
    public var hasFrom: Bool {
        _from != nil
    }

    /// Clears the value of `from`. Subsequent reads from it will return its default value.
    public mutating func clearFrom() {
        _from = nil
    }

    public var to: MobileTesting_Point {
        get { _to ?? MobileTesting_Point() }
        set { _to = newValue }
    }

    /// Returns true if `to` has been explicitly set.
    public var hasTo: Bool {
        _to != nil
    }

    /// Clears the value of `to`. Subsequent reads from it will return its default value.
    public mutating func clearTo() {
        _to = nil
    }

    public var duration: MobileTesting_Duration {
        get { _duration ?? MobileTesting_Duration() }
        set { _duration = newValue }
    }

    /// Returns true if `duration` has been explicitly set.
    public var hasDuration: Bool {
        _duration != nil
    }

    /// Clears the value of `duration`. Subsequent reads from it will return its default value.
    public mutating func clearDuration() {
        _duration = nil
    }

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _from: MobileTesting_Point?
    fileprivate var _to: MobileTesting_Point?
    fileprivate var _duration: MobileTesting_Duration?
}

public struct MobileTesting_SwipeDirectionRequest: Sendable {
    public var direction: MobileTesting_Direction = .unspecified
    public var distance: Float = 0
    public var durationMs: Int32 = 0
    public var selector: MobileTesting_ElementSelector {
        get { _selector ?? MobileTesting_ElementSelector() }
        set { _selector = newValue }
    }
    public var hasSelector: Bool { _selector != nil }
    public mutating func clearSelector() { _selector = nil }
    public var unknownFields = SwiftProtobuf.UnknownStorage()
    public init() {}
    fileprivate var _selector: MobileTesting_ElementSelector?
}

public struct MobileTesting_ScrollRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var direction: MobileTesting_Direction = .unspecified

    public var distance: Float = 0

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct MobileTesting_ScrollToElementRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var selector: MobileTesting_ElementSelector {
        get { _selector ?? MobileTesting_ElementSelector() }
        set { _selector = newValue }
    }

    /// Returns true if `selector` has been explicitly set.
    public var hasSelector: Bool {
        _selector != nil
    }

    /// Clears the value of `selector`. Subsequent reads from it will return its default value.
    public mutating func clearSelector() {
        _selector = nil
    }

    public var direction: MobileTesting_Direction = .unspecified

    public var maxScrolls: Int32 = 0

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _selector: MobileTesting_ElementSelector?
}

public struct MobileTesting_PinchRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var center: MobileTesting_Point {
        get { _center ?? MobileTesting_Point() }
        set { _center = newValue }
    }

    /// Returns true if `center` has been explicitly set.
    public var hasCenter: Bool {
        _center != nil
    }

    /// Clears the value of `center`. Subsequent reads from it will return its default value.
    public mutating func clearCenter() {
        _center = nil
    }

    public var scale: Float = 0

    public var velocity: Float = 0

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _center: MobileTesting_Point?
}

public struct MobileTesting_DragRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var from: MobileTesting_Point {
        get { _from ?? MobileTesting_Point() }
        set { _from = newValue }
    }

    /// Returns true if `from` has been explicitly set.
    public var hasFrom: Bool {
        _from != nil
    }

    /// Clears the value of `from`. Subsequent reads from it will return its default value.
    public mutating func clearFrom() {
        _from = nil
    }

    public var to: MobileTesting_Point {
        get { _to ?? MobileTesting_Point() }
        set { _to = newValue }
    }

    /// Returns true if `to` has been explicitly set.
    public var hasTo: Bool {
        _to != nil
    }

    /// Clears the value of `to`. Subsequent reads from it will return its default value.
    public mutating func clearTo() {
        _to = nil
    }

    public var duration: MobileTesting_Duration {
        get { _duration ?? MobileTesting_Duration() }
        set { _duration = newValue }
    }

    /// Returns true if `duration` has been explicitly set.
    public var hasDuration: Bool {
        _duration != nil
    }

    /// Clears the value of `duration`. Subsequent reads from it will return its default value.
    public mutating func clearDuration() {
        _duration = nil
    }

    public var holdDuration: MobileTesting_Duration {
        get { _holdDuration ?? MobileTesting_Duration() }
        set { _holdDuration = newValue }
    }

    /// Returns true if `holdDuration` has been explicitly set.
    public var hasHoldDuration: Bool {
        _holdDuration != nil
    }

    /// Clears the value of `holdDuration`. Subsequent reads from it will return its default value.
    public mutating func clearHoldDuration() {
        _holdDuration = nil
    }

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _from: MobileTesting_Point?
    fileprivate var _to: MobileTesting_Point?
    fileprivate var _duration: MobileTesting_Duration?
    fileprivate var _holdDuration: MobileTesting_Duration?
}

public struct MobileTesting_TypeTextRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var text: String = .init()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct MobileTesting_ClearTextRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var characterCount: Int32 = 0

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct MobileTesting_SetTextRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var selector: MobileTesting_ElementSelector {
        get { _selector ?? MobileTesting_ElementSelector() }
        set { _selector = newValue }
    }

    /// Returns true if `selector` has been explicitly set.
    public var hasSelector: Bool {
        _selector != nil
    }

    /// Clears the value of `selector`. Subsequent reads from it will return its default value.
    public mutating func clearSelector() {
        _selector = nil
    }

    public var text: String = .init()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _selector: MobileTesting_ElementSelector?
}

public struct MobileTesting_ScreenshotRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var format: String = .init()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct MobileTesting_ScreenshotResponse: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var data: Data = .init()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct MobileTesting_KeyboardVisibleResponse: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var visible: Bool = false

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

private let _protobuf_package = "mobile.testing.v1"

extension MobileTesting_StartSessionRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding
{
    public static let protoMessageName: String = _protobuf_package + ".StartSessionRequest"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}requested_session_id\0\u{3}app_id\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularStringField(value: &requestedSessionID)
            case 2: try decoder.decodeSingularStringField(value: &appID)
            default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !requestedSessionID.isEmpty {
            try visitor.visitSingularStringField(value: requestedSessionID, fieldNumber: 1)
        }
        if !appID.isEmpty {
            try visitor.visitSingularStringField(value: appID, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: MobileTesting_StartSessionRequest, rhs: MobileTesting_StartSessionRequest) -> Bool {
        if lhs.requestedSessionID != rhs.requestedSessionID { return false }
        if lhs.appID != rhs.appID { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension MobileTesting_StartSessionResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding
{
    public static let protoMessageName: String = _protobuf_package + ".StartSessionResponse"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}session_id\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularStringField(value: &sessionID)
            default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !sessionID.isEmpty {
            try visitor.visitSingularStringField(value: sessionID, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: MobileTesting_StartSessionResponse, rhs: MobileTesting_StartSessionResponse) -> Bool {
        if lhs.sessionID != rhs.sessionID { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension MobileTesting_CapabilitiesRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding
{
    public static let protoMessageName: String = _protobuf_package + ".CapabilitiesRequest"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        // Load everything into unknown fields
        while try decoder.nextFieldNumber() != nil {}
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: MobileTesting_CapabilitiesRequest, rhs: MobileTesting_CapabilitiesRequest) -> Bool {
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension MobileTesting_CapabilitiesResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding
{
    public static let protoMessageName: String = _protobuf_package + ".CapabilitiesResponse"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}capabilities\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeRepeatedMessageField(value: &capabilities)
            default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !capabilities.isEmpty {
            try visitor.visitRepeatedMessageField(value: capabilities, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: MobileTesting_CapabilitiesResponse, rhs: MobileTesting_CapabilitiesResponse) -> Bool {
        if lhs.capabilities != rhs.capabilities { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension MobileTesting_EndSessionRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding
{
    public static let protoMessageName: String = _protobuf_package + ".EndSessionRequest"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}session_id\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularStringField(value: &sessionID)
            default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !sessionID.isEmpty {
            try visitor.visitSingularStringField(value: sessionID, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: MobileTesting_EndSessionRequest, rhs: MobileTesting_EndSessionRequest) -> Bool {
        if lhs.sessionID != rhs.sessionID { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension MobileTesting_EndSessionResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding
{
    public static let protoMessageName: String = _protobuf_package + ".EndSessionResponse"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}ended\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularBoolField(value: &ended)
            default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if ended != false {
            try visitor.visitSingularBoolField(value: ended, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: MobileTesting_EndSessionResponse, rhs: MobileTesting_EndSessionResponse) -> Bool {
        if lhs.ended != rhs.ended { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension MobileTesting_TapRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding
{
    public static let protoMessageName: String = _protobuf_package + ".TapRequest"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}point\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularMessageField(value: &_point)
            default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        if let v = _point {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: MobileTesting_TapRequest, rhs: MobileTesting_TapRequest) -> Bool {
        if lhs._point != rhs._point { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension MobileTesting_LongPressRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding
{
    public static let protoMessageName: String = _protobuf_package + ".LongPressRequest"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}point\0\u{1}duration\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularMessageField(value: &_point)
            case 2: try decoder.decodeSingularMessageField(value: &_duration)
            default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        if let v = _point {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
        }
        try { if let v = self._duration {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
        } }()
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: MobileTesting_LongPressRequest, rhs: MobileTesting_LongPressRequest) -> Bool {
        if lhs._point != rhs._point { return false }
        if lhs._duration != rhs._duration { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension MobileTesting_TapElementRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding
{
    public static let protoMessageName: String = _protobuf_package + ".TapElementRequest"
    public static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(bytecode: "\0\u{1}selector\0\u{3}app_id\0\u{3}candidate_bundle_ids\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularMessageField(value: &_selector)
            case 2: try decoder.decodeSingularStringField(value: &appID)
            case 3: try decoder.decodeRepeatedStringField(value: &candidateBundleIds)
            default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        if let v = _selector {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
        }
        if !appID.isEmpty {
            try visitor.visitSingularStringField(value: appID, fieldNumber: 2)
        }
        if !candidateBundleIds.isEmpty {
            try visitor.visitRepeatedStringField(value: candidateBundleIds, fieldNumber: 3)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: MobileTesting_TapElementRequest, rhs: MobileTesting_TapElementRequest) -> Bool {
        if lhs._selector != rhs._selector { return false }
        if lhs.appID != rhs.appID { return false }
        if lhs.candidateBundleIds != rhs.candidateBundleIds { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension MobileTesting_SwipeRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding
{
    public static let protoMessageName: String = _protobuf_package + ".SwipeRequest"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}from\0\u{1}to\0\u{1}duration\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularMessageField(value: &_from)
            case 2: try decoder.decodeSingularMessageField(value: &_to)
            case 3: try decoder.decodeSingularMessageField(value: &_duration)
            default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        if let v = _from {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
        }
        try { if let v = self._to {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
        } }()
        try { if let v = self._duration {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
        } }()
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: MobileTesting_SwipeRequest, rhs: MobileTesting_SwipeRequest) -> Bool {
        if lhs._from != rhs._from { return false }
        if lhs._to != rhs._to { return false }
        if lhs._duration != rhs._duration { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension MobileTesting_SwipeDirectionRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding
{
    public static let protoMessageName: String = _protobuf_package + ".SwipeDirectionRequest"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}direction\0\u{1}distance\0\u{3}duration_ms\0\u{1}selector\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            switch fieldNumber {
            case 1: try decoder.decodeSingularEnumField(value: &direction)
            case 2: try decoder.decodeSingularFloatField(value: &distance)
            case 3: try decoder.decodeSingularInt32Field(value: &durationMs)
            case 4: try decoder.decodeSingularMessageField(value: &_selector)
            default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if direction != .unspecified {
            try visitor.visitSingularEnumField(value: direction, fieldNumber: 1)
        }
        if distance.bitPattern != 0 {
            try visitor.visitSingularFloatField(value: distance, fieldNumber: 2)
        }
        if durationMs != 0 {
            try visitor.visitSingularInt32Field(value: durationMs, fieldNumber: 3)
        }
        if let v = _selector {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (
        lhs: MobileTesting_SwipeDirectionRequest,
        rhs: MobileTesting_SwipeDirectionRequest
    ) -> Bool {
        if lhs.direction != rhs.direction { return false }
        if lhs.distance != rhs.distance { return false }
        if lhs.durationMs != rhs.durationMs { return false }
        if lhs._selector != rhs._selector { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension MobileTesting_ScrollRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding
{
    public static let protoMessageName: String = _protobuf_package + ".ScrollRequest"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}direction\0\u{1}distance\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularEnumField(value: &direction)
            case 2: try decoder.decodeSingularFloatField(value: &distance)
            default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if direction != .unspecified {
            try visitor.visitSingularEnumField(value: direction, fieldNumber: 1)
        }
        if distance.bitPattern != 0 {
            try visitor.visitSingularFloatField(value: distance, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: MobileTesting_ScrollRequest, rhs: MobileTesting_ScrollRequest) -> Bool {
        if lhs.direction != rhs.direction { return false }
        if lhs.distance != rhs.distance { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension MobileTesting_ScrollToElementRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding
{
    public static let protoMessageName: String = _protobuf_package + ".ScrollToElementRequest"
    public static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(bytecode: "\0\u{1}selector\0\u{1}direction\0\u{3}max_scrolls\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularMessageField(value: &_selector)
            case 2: try decoder.decodeSingularEnumField(value: &direction)
            case 3: try decoder.decodeSingularInt32Field(value: &maxScrolls)
            default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        if let v = _selector {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
        }
        if direction != .unspecified {
            try visitor.visitSingularEnumField(value: direction, fieldNumber: 2)
        }
        if maxScrolls != 0 {
            try visitor.visitSingularInt32Field(value: maxScrolls, fieldNumber: 3)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (
        lhs: MobileTesting_ScrollToElementRequest,
        rhs: MobileTesting_ScrollToElementRequest
    ) -> Bool {
        if lhs._selector != rhs._selector { return false }
        if lhs.direction != rhs.direction { return false }
        if lhs.maxScrolls != rhs.maxScrolls { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension MobileTesting_PinchRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding
{
    public static let protoMessageName: String = _protobuf_package + ".PinchRequest"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}center\0\u{1}scale\0\u{1}velocity\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularMessageField(value: &_center)
            case 2: try decoder.decodeSingularFloatField(value: &scale)
            case 3: try decoder.decodeSingularFloatField(value: &velocity)
            default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        if let v = _center {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
        }
        if scale.bitPattern != 0 {
            try visitor.visitSingularFloatField(value: scale, fieldNumber: 2)
        }
        if velocity.bitPattern != 0 {
            try visitor.visitSingularFloatField(value: velocity, fieldNumber: 3)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: MobileTesting_PinchRequest, rhs: MobileTesting_PinchRequest) -> Bool {
        if lhs._center != rhs._center { return false }
        if lhs.scale != rhs.scale { return false }
        if lhs.velocity != rhs.velocity { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension MobileTesting_DragRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding
{
    public static let protoMessageName: String = _protobuf_package + ".DragRequest"
    public static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(bytecode: "\0\u{1}from\0\u{1}to\0\u{1}duration\0\u{3}hold_duration\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularMessageField(value: &_from)
            case 2: try decoder.decodeSingularMessageField(value: &_to)
            case 3: try decoder.decodeSingularMessageField(value: &_duration)
            case 4: try decoder.decodeSingularMessageField(value: &_holdDuration)
            default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        if let v = _from {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
        }
        try { if let v = self._to {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
        } }()
        try { if let v = self._duration {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
        } }()
        try { if let v = self._holdDuration {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
        } }()
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: MobileTesting_DragRequest, rhs: MobileTesting_DragRequest) -> Bool {
        if lhs._from != rhs._from { return false }
        if lhs._to != rhs._to { return false }
        if lhs._duration != rhs._duration { return false }
        if lhs._holdDuration != rhs._holdDuration { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension MobileTesting_TypeTextRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding
{
    public static let protoMessageName: String = _protobuf_package + ".TypeTextRequest"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}text\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularStringField(value: &text)
            default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !text.isEmpty {
            try visitor.visitSingularStringField(value: text, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: MobileTesting_TypeTextRequest, rhs: MobileTesting_TypeTextRequest) -> Bool {
        if lhs.text != rhs.text { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension MobileTesting_ClearTextRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding
{
    public static let protoMessageName: String = _protobuf_package + ".ClearTextRequest"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}character_count\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularInt32Field(value: &characterCount)
            default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if characterCount != 0 {
            try visitor.visitSingularInt32Field(value: characterCount, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: MobileTesting_ClearTextRequest, rhs: MobileTesting_ClearTextRequest) -> Bool {
        if lhs.characterCount != rhs.characterCount { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension MobileTesting_SetTextRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding
{
    public static let protoMessageName: String = _protobuf_package + ".SetTextRequest"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}selector\0\u{1}text\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularMessageField(value: &_selector)
            case 2: try decoder.decodeSingularStringField(value: &text)
            default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        if let v = _selector {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
        }
        if !text.isEmpty {
            try visitor.visitSingularStringField(value: text, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: MobileTesting_SetTextRequest, rhs: MobileTesting_SetTextRequest) -> Bool {
        if lhs._selector != rhs._selector { return false }
        if lhs.text != rhs.text { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension MobileTesting_ScreenshotRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding
{
    public static let protoMessageName: String = _protobuf_package + ".ScreenshotRequest"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}format\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularStringField(value: &format)
            default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !format.isEmpty {
            try visitor.visitSingularStringField(value: format, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: MobileTesting_ScreenshotRequest, rhs: MobileTesting_ScreenshotRequest) -> Bool {
        if lhs.format != rhs.format { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension MobileTesting_ScreenshotResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding
{
    public static let protoMessageName: String = _protobuf_package + ".ScreenshotResponse"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}data\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularBytesField(value: &data)
            default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !data.isEmpty {
            try visitor.visitSingularBytesField(value: data, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: MobileTesting_ScreenshotResponse, rhs: MobileTesting_ScreenshotResponse) -> Bool {
        if lhs.data != rhs.data { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension MobileTesting_KeyboardVisibleResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding
{
    public static let protoMessageName: String = _protobuf_package + ".KeyboardVisibleResponse"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}visible\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularBoolField(value: &visible)
            default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if visible != false {
            try visitor.visitSingularBoolField(value: visible, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (
        lhs: MobileTesting_KeyboardVisibleResponse,
        rhs: MobileTesting_KeyboardVisibleResponse
    ) -> Bool {
        if lhs.visible != rhs.visible { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}
