// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: common.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

/// If the compiler emits an error on this type, it is because this file
/// was generated by a version of the `protoc` Swift plug-in that is
/// incompatible with the version of SwiftProtobuf to which you are linking.
/// Please ensure that you are building against the same version of the API
/// that was used to generate this file.
private struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
    struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
    typealias Version = _2
}

public enum MobileTesting_CapabilityTier: SwiftProtobuf.Enum, Swift.CaseIterable {
    public typealias RawValue = Int
    case unspecified // = 0
    case required // = 1
    case optional // = 2
    case UNRECOGNIZED(Int)

    public init() {
        self = .unspecified
    }

    public init?(rawValue: Int) {
        switch rawValue {
        case 0: self = .unspecified
        case 1: self = .required
        case 2: self = .optional
        default: self = .UNRECOGNIZED(rawValue)
        }
    }

    public var rawValue: Int {
        switch self {
        case .unspecified: 0
        case .required: 1
        case .optional: 2
        case let .UNRECOGNIZED(i): i
        }
    }

    /// The compiler won't synthesize support with the UNRECOGNIZED case.
    public static let allCases: [MobileTesting_CapabilityTier] = [
        .unspecified,
        .required,
        .optional
    ]
}

public enum MobileTesting_Direction: SwiftProtobuf.Enum, Swift.CaseIterable {
    public typealias RawValue = Int
    case unspecified // = 0
    case up // = 1
    case down // = 2
    case left // = 3
    case right // = 4
    case UNRECOGNIZED(Int)

    public init() {
        self = .unspecified
    }

    public init?(rawValue: Int) {
        switch rawValue {
        case 0: self = .unspecified
        case 1: self = .up
        case 2: self = .down
        case 3: self = .left
        case 4: self = .right
        default: self = .UNRECOGNIZED(rawValue)
        }
    }

    public var rawValue: Int {
        switch self {
        case .unspecified: 0
        case .up: 1
        case .down: 2
        case .left: 3
        case .right: 4
        case let .UNRECOGNIZED(i): i
        }
    }

    /// The compiler won't synthesize support with the UNRECOGNIZED case.
    public static let allCases: [MobileTesting_Direction] = [
        .unspecified,
        .up,
        .down,
        .left,
        .right
    ]
}

public struct MobileTesting_Empty: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct MobileTesting_Point: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var x: Double = 0

    public var y: Double = 0

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct MobileTesting_Rect: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var x: Double = 0

    public var y: Double = 0

    public var width: Double = 0

    public var height: Double = 0

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct MobileTesting_Duration: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var milliseconds: Int32 = 0

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct MobileTesting_CapabilityDescriptor: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var key: String = .init()

    public var tier: MobileTesting_CapabilityTier = .unspecified

    public var supported: Bool = false

    public var reasonIfUnsupported: String = .init()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct MobileTesting_ElementSelector: @unchecked Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var id: String {
        get { _storage._id }
        set { _uniqueStorage()._id = newValue }
    }

    public var label: String {
        get { _storage._label }
        set { _uniqueStorage()._label = newValue }
    }

    public var containsText: String {
        get { _storage._containsText }
        set { _uniqueStorage()._containsText = newValue }
    }

    public var description_p: String {
        get { _storage._description_p }
        set { _uniqueStorage()._description_p = newValue }
    }

    public var parentSelector: MobileTesting_ElementSelector {
        get { _storage._parentSelector ?? MobileTesting_ElementSelector() }
        set { _uniqueStorage()._parentSelector = newValue }
    }

    /// Returns true if `parentSelector` has been explicitly set.
    public var hasParentSelector: Bool {
        _storage._parentSelector != nil
    }

    /// Clears the value of `parentSelector`. Subsequent reads from it will return its default value.
    public mutating func clearParentSelector() {
        _uniqueStorage()._parentSelector = nil
    }

    public var type: String {
        get { _storage._type }
        set { _uniqueStorage()._type = newValue }
    }

    public var value: String {
        get { _storage._value }
        set { _uniqueStorage()._value = newValue }
    }

    public var index: Int32 {
        get { _storage._index }
        set { _uniqueStorage()._index = newValue }
    }

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _storage = _StorageClass.defaultInstance
}

public struct MobileTesting_ElementInfo: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var id: String = .init()

    public var label: String = .init()

    public var value: String = .init()

    public var type: String = .init()

    public var frame: MobileTesting_Rect {
        get { _frame ?? MobileTesting_Rect() }
        set { _frame = newValue }
    }

    /// Returns true if `frame` has been explicitly set.
    public var hasFrame: Bool {
        _frame != nil
    }

    /// Clears the value of `frame`. Subsequent reads from it will return its default value.
    public mutating func clearFrame() {
        _frame = nil
    }

    public var isEnabled: Bool = false

    public var isVisible: Bool = false

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _frame: MobileTesting_Rect?
}

public struct MobileTesting_ViewNode: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var id: String = .init()

    public var label: String = .init()

    public var children: [MobileTesting_ViewNode] = []

    public var type: String = .init()

    public var value: String = .init()

    public var frame: MobileTesting_Rect {
        get { _frame ?? MobileTesting_Rect() }
        set { _frame = newValue }
    }

    /// Returns true if `frame` has been explicitly set.
    public var hasFrame: Bool {
        _frame != nil
    }

    /// Clears the value of `frame`. Subsequent reads from it will return its default value.
    public mutating func clearFrame() {
        _frame = nil
    }

    public var isEnabled: Bool = false

    public var isVisible: Bool = false

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _frame: MobileTesting_Rect?
}

public struct MobileTesting_ActionResponse: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var success: Bool = false

    public var message: String = .init()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

private let _protobuf_package = "mobile.testing.v1"

extension MobileTesting_CapabilityTier: SwiftProtobuf._ProtoNameProviding {
    public static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(
            bytecode: "\0\u{2}\0CAPABILITY_TIER_UNSPECIFIED\0\u{1}CAPABILITY_TIER_REQUIRED\0\u{1}CAPABILITY_TIER_OPTIONAL\0"
        )
}

extension MobileTesting_Direction: SwiftProtobuf._ProtoNameProviding {
    public static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(
            bytecode: "\0\u{2}\0DIRECTION_UNSPECIFIED\0\u{1}DIRECTION_UP\0\u{1}DIRECTION_DOWN\0\u{1}DIRECTION_LEFT\0\u{1}DIRECTION_RIGHT\0"
        )
}

extension MobileTesting_Empty: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding
{
    public static let protoMessageName: String = _protobuf_package + ".Empty"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        // Load everything into unknown fields
        while try decoder.nextFieldNumber() != nil {}
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: MobileTesting_Empty, rhs: MobileTesting_Empty) -> Bool {
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension MobileTesting_Point: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding
{
    public static let protoMessageName: String = _protobuf_package + ".Point"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}x\0\u{1}y\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularDoubleField(value: &x)
            case 2: try decoder.decodeSingularDoubleField(value: &y)
            default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if x.bitPattern != 0 {
            try visitor.visitSingularDoubleField(value: x, fieldNumber: 1)
        }
        if y.bitPattern != 0 {
            try visitor.visitSingularDoubleField(value: y, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: MobileTesting_Point, rhs: MobileTesting_Point) -> Bool {
        if lhs.x != rhs.x { return false }
        if lhs.y != rhs.y { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension MobileTesting_Rect: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding
{
    public static let protoMessageName: String = _protobuf_package + ".Rect"
    public static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(bytecode: "\0\u{1}x\0\u{1}y\0\u{1}width\0\u{1}height\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularDoubleField(value: &x)
            case 2: try decoder.decodeSingularDoubleField(value: &y)
            case 3: try decoder.decodeSingularDoubleField(value: &width)
            case 4: try decoder.decodeSingularDoubleField(value: &height)
            default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if x.bitPattern != 0 {
            try visitor.visitSingularDoubleField(value: x, fieldNumber: 1)
        }
        if y.bitPattern != 0 {
            try visitor.visitSingularDoubleField(value: y, fieldNumber: 2)
        }
        if width.bitPattern != 0 {
            try visitor.visitSingularDoubleField(value: width, fieldNumber: 3)
        }
        if height.bitPattern != 0 {
            try visitor.visitSingularDoubleField(value: height, fieldNumber: 4)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: MobileTesting_Rect, rhs: MobileTesting_Rect) -> Bool {
        if lhs.x != rhs.x { return false }
        if lhs.y != rhs.y { return false }
        if lhs.width != rhs.width { return false }
        if lhs.height != rhs.height { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension MobileTesting_Duration: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding
{
    public static let protoMessageName: String = _protobuf_package + ".Duration"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}milliseconds\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularInt32Field(value: &milliseconds)
            default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if milliseconds != 0 {
            try visitor.visitSingularInt32Field(value: milliseconds, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: MobileTesting_Duration, rhs: MobileTesting_Duration) -> Bool {
        if lhs.milliseconds != rhs.milliseconds { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension MobileTesting_CapabilityDescriptor: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding
{
    public static let protoMessageName: String = _protobuf_package + ".CapabilityDescriptor"
    public static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(bytecode: "\0\u{1}key\0\u{1}tier\0\u{1}supported\0\u{3}reason_if_unsupported\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularStringField(value: &key)
            case 2: try decoder.decodeSingularEnumField(value: &tier)
            case 3: try decoder.decodeSingularBoolField(value: &supported)
            case 4: try decoder.decodeSingularStringField(value: &reasonIfUnsupported)
            default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !key.isEmpty {
            try visitor.visitSingularStringField(value: key, fieldNumber: 1)
        }
        if tier != .unspecified {
            try visitor.visitSingularEnumField(value: tier, fieldNumber: 2)
        }
        if supported != false {
            try visitor.visitSingularBoolField(value: supported, fieldNumber: 3)
        }
        if !reasonIfUnsupported.isEmpty {
            try visitor.visitSingularStringField(value: reasonIfUnsupported, fieldNumber: 4)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: MobileTesting_CapabilityDescriptor, rhs: MobileTesting_CapabilityDescriptor) -> Bool {
        if lhs.key != rhs.key { return false }
        if lhs.tier != rhs.tier { return false }
        if lhs.supported != rhs.supported { return false }
        if lhs.reasonIfUnsupported != rhs.reasonIfUnsupported { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension MobileTesting_ElementSelector: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding
{
    public static let protoMessageName: String = _protobuf_package + ".ElementSelector"
    public static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(
            bytecode: "\0\u{1}id\0\u{1}label\0\u{3}contains_text\0\u{1}description\0\u{3}parent_selector\0\u{1}type\0\u{1}value\0\u{1}index\0"
        )

    fileprivate class _StorageClass {
        var _id: String = .init()
        var _label: String = .init()
        var _containsText: String = .init()
        var _description_p: String = .init()
        var _parentSelector: MobileTesting_ElementSelector?
        var _type: String = .init()
        var _value: String = .init()
        var _index: Int32 = 0

        /// This property is used as the initial default value for new instances of the type.
        /// The type itself is protecting the reference to its storage via CoW semantics.
        /// This will force a copy to be made of this reference when the first mutation occurs;
        /// hence, it is safe to mark this as `nonisolated(unsafe)`.
        nonisolated(unsafe) static let defaultInstance = _StorageClass()

        private init() {}

        init(copying source: _StorageClass) {
            _id = source._id
            _label = source._label
            _containsText = source._containsText
            _description_p = source._description_p
            _parentSelector = source._parentSelector
            _type = source._type
            _value = source._value
            _index = source._index
        }
    }

    fileprivate mutating func _uniqueStorage() -> _StorageClass {
        if !isKnownUniquelyReferenced(&_storage) {
            _storage = _StorageClass(copying: _storage)
        }
        return _storage
    }

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        _ = _uniqueStorage()
        try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
            while let fieldNumber = try decoder.nextFieldNumber() {
                // The use of inline closures is to circumvent an issue where the compiler
                // allocates stack space for every case branch when no optimizations are
                // enabled. https://github.com/apple/swift-protobuf/issues/1034
                switch fieldNumber {
                case 1: try decoder.decodeSingularStringField(value: &_storage._id)
                case 2: try decoder.decodeSingularStringField(value: &_storage._label)
                case 3: try decoder.decodeSingularStringField(value: &_storage._containsText)
                case 4: try decoder.decodeSingularStringField(value: &_storage._description_p)
                case 5: try decoder.decodeSingularMessageField(value: &_storage._parentSelector)
                case 6: try decoder.decodeSingularStringField(value: &_storage._type)
                case 7: try decoder.decodeSingularStringField(value: &_storage._value)
                case 8: try decoder.decodeSingularInt32Field(value: &_storage._index)
                default: break
                }
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every if/case branch local when no optimizations
            // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
            // https://github.com/apple/swift-protobuf/issues/1182
            if !_storage._id.isEmpty {
                try visitor.visitSingularStringField(value: _storage._id, fieldNumber: 1)
            }
            if !_storage._label.isEmpty {
                try visitor.visitSingularStringField(value: _storage._label, fieldNumber: 2)
            }
            if !_storage._containsText.isEmpty {
                try visitor.visitSingularStringField(value: _storage._containsText, fieldNumber: 3)
            }
            if !_storage._description_p.isEmpty {
                try visitor.visitSingularStringField(value: _storage._description_p, fieldNumber: 4)
            }
            try { if let v = _storage._parentSelector {
                try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
            } }()
            if !_storage._type.isEmpty {
                try visitor.visitSingularStringField(value: _storage._type, fieldNumber: 6)
            }
            if !_storage._value.isEmpty {
                try visitor.visitSingularStringField(value: _storage._value, fieldNumber: 7)
            }
            if _storage._index != 0 {
                try visitor.visitSingularInt32Field(value: _storage._index, fieldNumber: 8)
            }
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: MobileTesting_ElementSelector, rhs: MobileTesting_ElementSelector) -> Bool {
        if lhs._storage !== rhs._storage {
            let storagesAreEqual: Bool = withExtendedLifetime((
                lhs._storage,
                rhs._storage
            )) { (_args: (_StorageClass, _StorageClass)) in
                let _storage = _args.0
                let rhs_storage = _args.1
                if _storage._id != rhs_storage._id { return false }
                if _storage._label != rhs_storage._label { return false }
                if _storage._containsText != rhs_storage._containsText { return false }
                if _storage._description_p != rhs_storage._description_p { return false }
                if _storage._parentSelector != rhs_storage._parentSelector { return false }
                if _storage._type != rhs_storage._type { return false }
                if _storage._value != rhs_storage._value { return false }
                if _storage._index != rhs_storage._index { return false }
                return true
            }
            if !storagesAreEqual { return false }
        }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension MobileTesting_ElementInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding
{
    public static let protoMessageName: String = _protobuf_package + ".ElementInfo"
    public static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(
            bytecode: "\0\u{1}id\0\u{1}label\0\u{1}value\0\u{1}type\0\u{1}frame\0\u{3}is_enabled\0\u{3}is_visible\0"
        )

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularStringField(value: &id)
            case 2: try decoder.decodeSingularStringField(value: &label)
            case 3: try decoder.decodeSingularStringField(value: &value)
            case 4: try decoder.decodeSingularStringField(value: &type)
            case 5: try decoder.decodeSingularMessageField(value: &_frame)
            case 6: try decoder.decodeSingularBoolField(value: &isEnabled)
            case 7: try decoder.decodeSingularBoolField(value: &isVisible)
            default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        if !id.isEmpty {
            try visitor.visitSingularStringField(value: id, fieldNumber: 1)
        }
        if !label.isEmpty {
            try visitor.visitSingularStringField(value: label, fieldNumber: 2)
        }
        if !value.isEmpty {
            try visitor.visitSingularStringField(value: value, fieldNumber: 3)
        }
        if !type.isEmpty {
            try visitor.visitSingularStringField(value: type, fieldNumber: 4)
        }
        try { if let v = self._frame {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
        } }()
        if isEnabled != false {
            try visitor.visitSingularBoolField(value: isEnabled, fieldNumber: 6)
        }
        if isVisible != false {
            try visitor.visitSingularBoolField(value: isVisible, fieldNumber: 7)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: MobileTesting_ElementInfo, rhs: MobileTesting_ElementInfo) -> Bool {
        if lhs.id != rhs.id { return false }
        if lhs.label != rhs.label { return false }
        if lhs.value != rhs.value { return false }
        if lhs.type != rhs.type { return false }
        if lhs._frame != rhs._frame { return false }
        if lhs.isEnabled != rhs.isEnabled { return false }
        if lhs.isVisible != rhs.isVisible { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension MobileTesting_ViewNode: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding
{
    public static let protoMessageName: String = _protobuf_package + ".ViewNode"
    public static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(
            bytecode: "\0\u{1}id\0\u{1}label\0\u{1}children\0\u{1}type\0\u{1}value\0\u{1}frame\0\u{3}is_enabled\0\u{3}is_visible\0"
        )

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularStringField(value: &id)
            case 2: try decoder.decodeSingularStringField(value: &label)
            case 3: try decoder.decodeRepeatedMessageField(value: &children)
            case 4: try decoder.decodeSingularStringField(value: &type)
            case 5: try decoder.decodeSingularStringField(value: &value)
            case 6: try decoder.decodeSingularMessageField(value: &_frame)
            case 7: try decoder.decodeSingularBoolField(value: &isEnabled)
            case 8: try decoder.decodeSingularBoolField(value: &isVisible)
            default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        if !id.isEmpty {
            try visitor.visitSingularStringField(value: id, fieldNumber: 1)
        }
        if !label.isEmpty {
            try visitor.visitSingularStringField(value: label, fieldNumber: 2)
        }
        if !children.isEmpty {
            try visitor.visitRepeatedMessageField(value: children, fieldNumber: 3)
        }
        if !type.isEmpty {
            try visitor.visitSingularStringField(value: type, fieldNumber: 4)
        }
        if !value.isEmpty {
            try visitor.visitSingularStringField(value: value, fieldNumber: 5)
        }
        try { if let v = self._frame {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
        } }()
        if isEnabled != false {
            try visitor.visitSingularBoolField(value: isEnabled, fieldNumber: 7)
        }
        if isVisible != false {
            try visitor.visitSingularBoolField(value: isVisible, fieldNumber: 8)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: MobileTesting_ViewNode, rhs: MobileTesting_ViewNode) -> Bool {
        if lhs.id != rhs.id { return false }
        if lhs.label != rhs.label { return false }
        if lhs.children != rhs.children { return false }
        if lhs.type != rhs.type { return false }
        if lhs.value != rhs.value { return false }
        if lhs._frame != rhs._frame { return false }
        if lhs.isEnabled != rhs.isEnabled { return false }
        if lhs.isVisible != rhs.isVisible { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension MobileTesting_ActionResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding
{
    public static let protoMessageName: String = _protobuf_package + ".ActionResponse"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}success\0\u{1}message\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularBoolField(value: &success)
            case 2: try decoder.decodeSingularStringField(value: &message)
            default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if success != false {
            try visitor.visitSingularBoolField(value: success, fieldNumber: 1)
        }
        if !message.isEmpty {
            try visitor.visitSingularStringField(value: message, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: MobileTesting_ActionResponse, rhs: MobileTesting_ActionResponse) -> Bool {
        if lhs.success != rhs.success { return false }
        if lhs.message != rhs.message { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}
