// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: common.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated enum Amoo_CapabilityTier: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case `required` // = 1
  case `optional` // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .required
    case 2: self = .optional
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .required: return 1
    case .optional: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Amoo_CapabilityTier] = [
    .unspecified,
    .required,
    .optional,
  ]

}

public nonisolated enum Amoo_Direction: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case up // = 1
  case down // = 2
  case left // = 3
  case right // = 4
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .up
    case 2: self = .down
    case 3: self = .left
    case 4: self = .right
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .up: return 1
    case .down: return 2
    case .left: return 3
    case .right: return 4
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Amoo_Direction] = [
    .unspecified,
    .up,
    .down,
    .left,
    .right,
  ]

}

public nonisolated struct Amoo_Empty: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Amoo_Point: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var x: Double = 0

  public var y: Double = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Amoo_Rect: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var x: Double = 0

  public var y: Double = 0

  public var width: Double = 0

  public var height: Double = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Amoo_Duration: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var milliseconds: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Amoo_CapabilityDescriptor: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var key: String = String()

  public var tier: Amoo_CapabilityTier = .unspecified

  public var supported: Bool = false

  public var reasonIfUnsupported: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Amoo_ElementSelector: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: String {
    get {_storage._id}
    set {_uniqueStorage()._id = newValue}
  }

  public var label: String {
    get {_storage._label}
    set {_uniqueStorage()._label = newValue}
  }

  public var containsText: String {
    get {_storage._containsText}
    set {_uniqueStorage()._containsText = newValue}
  }

  public var description_p: String {
    get {_storage._description_p}
    set {_uniqueStorage()._description_p = newValue}
  }

  public var parentSelector: Amoo_ElementSelector {
    get {_storage._parentSelector ?? Amoo_ElementSelector()}
    set {_uniqueStorage()._parentSelector = newValue}
  }
  /// Returns true if `parentSelector` has been explicitly set.
  public var hasParentSelector: Bool {_storage._parentSelector != nil}
  /// Clears the value of `parentSelector`. Subsequent reads from it will return its default value.
  public mutating func clearParentSelector() {_uniqueStorage()._parentSelector = nil}

  public var type: String {
    get {_storage._type}
    set {_uniqueStorage()._type = newValue}
  }

  public var value: String {
    get {_storage._value}
    set {_uniqueStorage()._value = newValue}
  }

  public var index: Int32 {
    get {_storage._index}
    set {_uniqueStorage()._index = newValue}
  }

  /// Restrict results to elements that carry an identifier or a label.
  ///
  /// Off by default: an unfiltered query returns unlabeled elements too, so an icon-only
  /// control with no accessibility label is still reachable by its frame rather than being
  /// invisible to every query. Set this when a caller wants only elements it can name —
  /// the screen summary does, since it describes a screen by what its elements are called.
  ///
  /// The accessibility reports deliberately leave it off: an element with neither identifier
  /// nor label is the finding they exist to produce.
  ///
  /// Has no effect alongside id/label/contains_text: an unlabeled element cannot match any
  /// of those anyway.
  public var labeledOnly: Bool {
    get {_storage._labeledOnly}
    set {_uniqueStorage()._labeledOnly = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

public nonisolated struct Amoo_ElementInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: String = String()

  public var label: String = String()

  public var value: String = String()

  public var type: String = String()

  public var frame: Amoo_Rect {
    get {_frame ?? Amoo_Rect()}
    set {_frame = newValue}
  }
  /// Returns true if `frame` has been explicitly set.
  public var hasFrame: Bool {self._frame != nil}
  /// Clears the value of `frame`. Subsequent reads from it will return its default value.
  public mutating func clearFrame() {self._frame = nil}

  public var isEnabled: Bool = false

  public var isVisible: Bool = false

  /// Preferred interaction coordinate in screen points. Unlike frame center, this is
  /// constrained to the portion of the element visible inside the current viewport.
  public var hitPoint: Amoo_Point {
    get {_hitPoint ?? Amoo_Point()}
    set {_hitPoint = newValue}
  }
  /// Returns true if `hitPoint` has been explicitly set.
  public var hasHitPoint: Bool {self._hitPoint != nil}
  /// Clears the value of `hitPoint`. Subsequent reads from it will return its default value.
  public mutating func clearHitPoint() {self._hitPoint = nil}

  public var isSecureTextEntry: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _frame: Amoo_Rect? = nil
  fileprivate var _hitPoint: Amoo_Point? = nil
}

public nonisolated struct Amoo_ViewNode: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: String = String()

  public var label: String = String()

  public var children: [Amoo_ViewNode] = []

  public var type: String = String()

  public var value: String = String()

  public var frame: Amoo_Rect {
    get {_frame ?? Amoo_Rect()}
    set {_frame = newValue}
  }
  /// Returns true if `frame` has been explicitly set.
  public var hasFrame: Bool {self._frame != nil}
  /// Clears the value of `frame`. Subsequent reads from it will return its default value.
  public mutating func clearFrame() {self._frame = nil}

  public var isEnabled: Bool = false

  public var isVisible: Bool = false

  public var hitPoint: Amoo_Point {
    get {_hitPoint ?? Amoo_Point()}
    set {_hitPoint = newValue}
  }
  /// Returns true if `hitPoint` has been explicitly set.
  public var hasHitPoint: Bool {self._hitPoint != nil}
  /// Clears the value of `hitPoint`. Subsequent reads from it will return its default value.
  public mutating func clearHitPoint() {self._hitPoint = nil}

  public var isSecureTextEntry: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _frame: Amoo_Rect? = nil
  fileprivate var _hitPoint: Amoo_Point? = nil
}

public nonisolated struct Amoo_ActionResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var success: Bool = false

  public var message: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "amoo.v1"

nonisolated extension Amoo_CapabilityTier: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0CAPABILITY_TIER_UNSPECIFIED\0\u{1}CAPABILITY_TIER_REQUIRED\0\u{1}CAPABILITY_TIER_OPTIONAL\0")
}

nonisolated extension Amoo_Direction: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0DIRECTION_UNSPECIFIED\0\u{1}DIRECTION_UP\0\u{1}DIRECTION_DOWN\0\u{1}DIRECTION_LEFT\0\u{1}DIRECTION_RIGHT\0")
}

nonisolated extension Amoo_Empty: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Empty"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Amoo_Empty, rhs: Amoo_Empty) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Amoo_Point: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Point"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}x\0\u{1}y\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularDoubleField(value: &self.x) }()
      case 2: try { try decoder.decodeSingularDoubleField(value: &self.y) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.x.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.x, fieldNumber: 1)
    }
    if self.y.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.y, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Amoo_Point, rhs: Amoo_Point) -> Bool {
    if lhs.x != rhs.x {return false}
    if lhs.y != rhs.y {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Amoo_Rect: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Rect"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}x\0\u{1}y\0\u{1}width\0\u{1}height\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularDoubleField(value: &self.x) }()
      case 2: try { try decoder.decodeSingularDoubleField(value: &self.y) }()
      case 3: try { try decoder.decodeSingularDoubleField(value: &self.width) }()
      case 4: try { try decoder.decodeSingularDoubleField(value: &self.height) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.x.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.x, fieldNumber: 1)
    }
    if self.y.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.y, fieldNumber: 2)
    }
    if self.width.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.width, fieldNumber: 3)
    }
    if self.height.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.height, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Amoo_Rect, rhs: Amoo_Rect) -> Bool {
    if lhs.x != rhs.x {return false}
    if lhs.y != rhs.y {return false}
    if lhs.width != rhs.width {return false}
    if lhs.height != rhs.height {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Amoo_Duration: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Duration"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}milliseconds\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.milliseconds) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.milliseconds != 0 {
      try visitor.visitSingularInt32Field(value: self.milliseconds, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Amoo_Duration, rhs: Amoo_Duration) -> Bool {
    if lhs.milliseconds != rhs.milliseconds {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Amoo_CapabilityDescriptor: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CapabilityDescriptor"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}key\0\u{1}tier\0\u{1}supported\0\u{3}reason_if_unsupported\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.key) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.tier) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.supported) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.reasonIfUnsupported) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.key.isEmpty {
      try visitor.visitSingularStringField(value: self.key, fieldNumber: 1)
    }
    if self.tier != .unspecified {
      try visitor.visitSingularEnumField(value: self.tier, fieldNumber: 2)
    }
    if self.supported != false {
      try visitor.visitSingularBoolField(value: self.supported, fieldNumber: 3)
    }
    if !self.reasonIfUnsupported.isEmpty {
      try visitor.visitSingularStringField(value: self.reasonIfUnsupported, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Amoo_CapabilityDescriptor, rhs: Amoo_CapabilityDescriptor) -> Bool {
    if lhs.key != rhs.key {return false}
    if lhs.tier != rhs.tier {return false}
    if lhs.supported != rhs.supported {return false}
    if lhs.reasonIfUnsupported != rhs.reasonIfUnsupported {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Amoo_ElementSelector: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ElementSelector"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}label\0\u{3}contains_text\0\u{1}description\0\u{3}parent_selector\0\u{1}type\0\u{1}value\0\u{1}index\0\u{3}labeled_only\0")

  fileprivate class _StorageClass {
    var _id: String = String()
    var _label: String = String()
    var _containsText: String = String()
    var _description_p: String = String()
    var _parentSelector: Amoo_ElementSelector? = nil
    var _type: String = String()
    var _value: String = String()
    var _index: Int32 = 0
    var _labeledOnly: Bool = false

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _id = source._id
      _label = source._label
      _containsText = source._containsText
      _description_p = source._description_p
      _parentSelector = source._parentSelector
      _type = source._type
      _value = source._value
      _index = source._index
      _labeledOnly = source._labeledOnly
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularStringField(value: &_storage._id) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._label) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._containsText) }()
        case 4: try { try decoder.decodeSingularStringField(value: &_storage._description_p) }()
        case 5: try { try decoder.decodeSingularMessageField(value: &_storage._parentSelector) }()
        case 6: try { try decoder.decodeSingularStringField(value: &_storage._type) }()
        case 7: try { try decoder.decodeSingularStringField(value: &_storage._value) }()
        case 8: try { try decoder.decodeSingularInt32Field(value: &_storage._index) }()
        case 9: try { try decoder.decodeSingularBoolField(value: &_storage._labeledOnly) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if !_storage._id.isEmpty {
        try visitor.visitSingularStringField(value: _storage._id, fieldNumber: 1)
      }
      if !_storage._label.isEmpty {
        try visitor.visitSingularStringField(value: _storage._label, fieldNumber: 2)
      }
      if !_storage._containsText.isEmpty {
        try visitor.visitSingularStringField(value: _storage._containsText, fieldNumber: 3)
      }
      if !_storage._description_p.isEmpty {
        try visitor.visitSingularStringField(value: _storage._description_p, fieldNumber: 4)
      }
      try { if let v = _storage._parentSelector {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      } }()
      if !_storage._type.isEmpty {
        try visitor.visitSingularStringField(value: _storage._type, fieldNumber: 6)
      }
      if !_storage._value.isEmpty {
        try visitor.visitSingularStringField(value: _storage._value, fieldNumber: 7)
      }
      if _storage._index != 0 {
        try visitor.visitSingularInt32Field(value: _storage._index, fieldNumber: 8)
      }
      if _storage._labeledOnly != false {
        try visitor.visitSingularBoolField(value: _storage._labeledOnly, fieldNumber: 9)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Amoo_ElementSelector, rhs: Amoo_ElementSelector) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._id != rhs_storage._id {return false}
        if _storage._label != rhs_storage._label {return false}
        if _storage._containsText != rhs_storage._containsText {return false}
        if _storage._description_p != rhs_storage._description_p {return false}
        if _storage._parentSelector != rhs_storage._parentSelector {return false}
        if _storage._type != rhs_storage._type {return false}
        if _storage._value != rhs_storage._value {return false}
        if _storage._index != rhs_storage._index {return false}
        if _storage._labeledOnly != rhs_storage._labeledOnly {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Amoo_ElementInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ElementInfo"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}label\0\u{1}value\0\u{1}type\0\u{1}frame\0\u{3}is_enabled\0\u{3}is_visible\0\u{3}hit_point\0\u{3}is_secure_text_entry\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.label) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.value) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.type) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._frame) }()
      case 6: try { try decoder.decodeSingularBoolField(value: &self.isEnabled) }()
      case 7: try { try decoder.decodeSingularBoolField(value: &self.isVisible) }()
      case 8: try { try decoder.decodeSingularMessageField(value: &self._hitPoint) }()
      case 9: try { try decoder.decodeSingularBoolField(value: &self.isSecureTextEntry) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.label.isEmpty {
      try visitor.visitSingularStringField(value: self.label, fieldNumber: 2)
    }
    if !self.value.isEmpty {
      try visitor.visitSingularStringField(value: self.value, fieldNumber: 3)
    }
    if !self.type.isEmpty {
      try visitor.visitSingularStringField(value: self.type, fieldNumber: 4)
    }
    try { if let v = self._frame {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    if self.isEnabled != false {
      try visitor.visitSingularBoolField(value: self.isEnabled, fieldNumber: 6)
    }
    if self.isVisible != false {
      try visitor.visitSingularBoolField(value: self.isVisible, fieldNumber: 7)
    }
    try { if let v = self._hitPoint {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    } }()
    if self.isSecureTextEntry != false {
      try visitor.visitSingularBoolField(value: self.isSecureTextEntry, fieldNumber: 9)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Amoo_ElementInfo, rhs: Amoo_ElementInfo) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.label != rhs.label {return false}
    if lhs.value != rhs.value {return false}
    if lhs.type != rhs.type {return false}
    if lhs._frame != rhs._frame {return false}
    if lhs.isEnabled != rhs.isEnabled {return false}
    if lhs.isVisible != rhs.isVisible {return false}
    if lhs._hitPoint != rhs._hitPoint {return false}
    if lhs.isSecureTextEntry != rhs.isSecureTextEntry {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Amoo_ViewNode: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ViewNode"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}label\0\u{1}children\0\u{1}type\0\u{1}value\0\u{1}frame\0\u{3}is_enabled\0\u{3}is_visible\0\u{3}hit_point\0\u{3}is_secure_text_entry\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.label) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.children) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.type) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.value) }()
      case 6: try { try decoder.decodeSingularMessageField(value: &self._frame) }()
      case 7: try { try decoder.decodeSingularBoolField(value: &self.isEnabled) }()
      case 8: try { try decoder.decodeSingularBoolField(value: &self.isVisible) }()
      case 9: try { try decoder.decodeSingularMessageField(value: &self._hitPoint) }()
      case 10: try { try decoder.decodeSingularBoolField(value: &self.isSecureTextEntry) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.label.isEmpty {
      try visitor.visitSingularStringField(value: self.label, fieldNumber: 2)
    }
    if !self.children.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.children, fieldNumber: 3)
    }
    if !self.type.isEmpty {
      try visitor.visitSingularStringField(value: self.type, fieldNumber: 4)
    }
    if !self.value.isEmpty {
      try visitor.visitSingularStringField(value: self.value, fieldNumber: 5)
    }
    try { if let v = self._frame {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    } }()
    if self.isEnabled != false {
      try visitor.visitSingularBoolField(value: self.isEnabled, fieldNumber: 7)
    }
    if self.isVisible != false {
      try visitor.visitSingularBoolField(value: self.isVisible, fieldNumber: 8)
    }
    try { if let v = self._hitPoint {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
    } }()
    if self.isSecureTextEntry != false {
      try visitor.visitSingularBoolField(value: self.isSecureTextEntry, fieldNumber: 10)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Amoo_ViewNode, rhs: Amoo_ViewNode) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.label != rhs.label {return false}
    if lhs.children != rhs.children {return false}
    if lhs.type != rhs.type {return false}
    if lhs.value != rhs.value {return false}
    if lhs._frame != rhs._frame {return false}
    if lhs.isEnabled != rhs.isEnabled {return false}
    if lhs.isVisible != rhs.isVisible {return false}
    if lhs._hitPoint != rhs._hitPoint {return false}
    if lhs.isSecureTextEntry != rhs.isSecureTextEntry {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Amoo_ActionResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ActionResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}success\0\u{1}message\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.success) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.message) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.success != false {
      try visitor.visitSingularBoolField(value: self.success, fieldNumber: 1)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Amoo_ActionResponse, rhs: Amoo_ActionResponse) -> Bool {
    if lhs.success != rhs.success {return false}
    if lhs.message != rhs.message {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
