// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: device.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

/// If the compiler emits an error on this type, it is because this file
/// was generated by a version of the `protoc` Swift plug-in that is
/// incompatible with the version of SwiftProtobuf to which you are linking.
/// Please ensure that you are building against the same version of the API
/// that was used to generate this file.
private struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
    struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
    typealias Version = _2
}

public struct MobileTesting_InstallAppRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var path: String = .init()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct MobileTesting_LaunchAppRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var appID: String = .init()

    public var arguments: [String] = []

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct MobileTesting_TerminateAppRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var appID: String = .init()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct MobileTesting_UninstallAppRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var appID: String = .init()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct MobileTesting_SetPermissionRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var appID: String = .init()

    public var permission: String = .init()

    public var granted: Bool = false

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct MobileTesting_SetLocationRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var latitude: Double = 0

    public var longitude: Double = 0

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct MobileTesting_SetAppearanceRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var appearance: String = .init()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct MobileTesting_OpenURLRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var url: String = .init()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

private let _protobuf_package = "mobile.testing.v1"

extension MobileTesting_InstallAppRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding
{
    public static let protoMessageName: String = _protobuf_package + ".InstallAppRequest"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}path\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularStringField(value: &path)
            default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !path.isEmpty {
            try visitor.visitSingularStringField(value: path, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: MobileTesting_InstallAppRequest, rhs: MobileTesting_InstallAppRequest) -> Bool {
        if lhs.path != rhs.path { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension MobileTesting_LaunchAppRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding
{
    public static let protoMessageName: String = _protobuf_package + ".LaunchAppRequest"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}app_id\0\u{1}arguments\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularStringField(value: &appID)
            case 2: try decoder.decodeRepeatedStringField(value: &arguments)
            default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !appID.isEmpty {
            try visitor.visitSingularStringField(value: appID, fieldNumber: 1)
        }
        if !arguments.isEmpty {
            try visitor.visitRepeatedStringField(value: arguments, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: MobileTesting_LaunchAppRequest, rhs: MobileTesting_LaunchAppRequest) -> Bool {
        if lhs.appID != rhs.appID { return false }
        if lhs.arguments != rhs.arguments { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension MobileTesting_TerminateAppRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding
{
    public static let protoMessageName: String = _protobuf_package + ".TerminateAppRequest"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}app_id\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularStringField(value: &appID)
            default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !appID.isEmpty {
            try visitor.visitSingularStringField(value: appID, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: MobileTesting_TerminateAppRequest, rhs: MobileTesting_TerminateAppRequest) -> Bool {
        if lhs.appID != rhs.appID { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension MobileTesting_UninstallAppRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding
{
    public static let protoMessageName: String = _protobuf_package + ".UninstallAppRequest"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}app_id\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularStringField(value: &appID)
            default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !appID.isEmpty {
            try visitor.visitSingularStringField(value: appID, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: MobileTesting_UninstallAppRequest, rhs: MobileTesting_UninstallAppRequest) -> Bool {
        if lhs.appID != rhs.appID { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension MobileTesting_SetPermissionRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding
{
    public static let protoMessageName: String = _protobuf_package + ".SetPermissionRequest"
    public static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(bytecode: "\0\u{3}app_id\0\u{1}permission\0\u{1}granted\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularStringField(value: &appID)
            case 2: try decoder.decodeSingularStringField(value: &permission)
            case 3: try decoder.decodeSingularBoolField(value: &granted)
            default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !appID.isEmpty {
            try visitor.visitSingularStringField(value: appID, fieldNumber: 1)
        }
        if !permission.isEmpty {
            try visitor.visitSingularStringField(value: permission, fieldNumber: 2)
        }
        if granted != false {
            try visitor.visitSingularBoolField(value: granted, fieldNumber: 3)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: MobileTesting_SetPermissionRequest, rhs: MobileTesting_SetPermissionRequest) -> Bool {
        if lhs.appID != rhs.appID { return false }
        if lhs.permission != rhs.permission { return false }
        if lhs.granted != rhs.granted { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension MobileTesting_SetLocationRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding
{
    public static let protoMessageName: String = _protobuf_package + ".SetLocationRequest"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}latitude\0\u{1}longitude\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularDoubleField(value: &latitude)
            case 2: try decoder.decodeSingularDoubleField(value: &longitude)
            default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if latitude.bitPattern != 0 {
            try visitor.visitSingularDoubleField(value: latitude, fieldNumber: 1)
        }
        if longitude.bitPattern != 0 {
            try visitor.visitSingularDoubleField(value: longitude, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: MobileTesting_SetLocationRequest, rhs: MobileTesting_SetLocationRequest) -> Bool {
        if lhs.latitude != rhs.latitude { return false }
        if lhs.longitude != rhs.longitude { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension MobileTesting_SetAppearanceRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding
{
    public static let protoMessageName: String = _protobuf_package + ".SetAppearanceRequest"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}appearance\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularStringField(value: &appearance)
            default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !appearance.isEmpty {
            try visitor.visitSingularStringField(value: appearance, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: MobileTesting_SetAppearanceRequest, rhs: MobileTesting_SetAppearanceRequest) -> Bool {
        if lhs.appearance != rhs.appearance { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension MobileTesting_OpenURLRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding
{
    public static let protoMessageName: String = _protobuf_package + ".OpenURLRequest"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}url\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularStringField(value: &url)
            default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !url.isEmpty {
            try visitor.visitSingularStringField(value: url, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: MobileTesting_OpenURLRequest, rhs: MobileTesting_OpenURLRequest) -> Bool {
        if lhs.url != rhs.url { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}
