// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: device.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - mobile.testing.v1.HostDeviceService

/// Namespace containing generated types for the "mobile.testing.v1.HostDeviceService" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum MobileTesting_HostDeviceService: Sendable {
    /// Service descriptor for the "mobile.testing.v1.HostDeviceService" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "mobile.testing.v1.HostDeviceService")
    /// Namespace for method metadata.
    public enum Method: Sendable {
        /// Namespace for "InstallApp" metadata.
        public enum InstallApp: Sendable {
            /// Request type for "InstallApp".
            public typealias Input = MobileTesting_InstallAppRequest
            /// Response type for "InstallApp".
            public typealias Output = MobileTesting_ActionResponse
            /// Descriptor for "InstallApp".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "mobile.testing.v1.HostDeviceService"),
                method: "InstallApp"
            )
        }
        /// Namespace for "LaunchApp" metadata.
        public enum LaunchApp: Sendable {
            /// Request type for "LaunchApp".
            public typealias Input = MobileTesting_LaunchAppRequest
            /// Response type for "LaunchApp".
            public typealias Output = MobileTesting_ActionResponse
            /// Descriptor for "LaunchApp".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "mobile.testing.v1.HostDeviceService"),
                method: "LaunchApp"
            )
        }
        /// Namespace for "TerminateApp" metadata.
        public enum TerminateApp: Sendable {
            /// Request type for "TerminateApp".
            public typealias Input = MobileTesting_TerminateAppRequest
            /// Response type for "TerminateApp".
            public typealias Output = MobileTesting_ActionResponse
            /// Descriptor for "TerminateApp".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "mobile.testing.v1.HostDeviceService"),
                method: "TerminateApp"
            )
        }
        /// Namespace for "UninstallApp" metadata.
        public enum UninstallApp: Sendable {
            /// Request type for "UninstallApp".
            public typealias Input = MobileTesting_UninstallAppRequest
            /// Response type for "UninstallApp".
            public typealias Output = MobileTesting_ActionResponse
            /// Descriptor for "UninstallApp".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "mobile.testing.v1.HostDeviceService"),
                method: "UninstallApp"
            )
        }
        /// Namespace for "SetPermission" metadata.
        public enum SetPermission: Sendable {
            /// Request type for "SetPermission".
            public typealias Input = MobileTesting_SetPermissionRequest
            /// Response type for "SetPermission".
            public typealias Output = MobileTesting_ActionResponse
            /// Descriptor for "SetPermission".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "mobile.testing.v1.HostDeviceService"),
                method: "SetPermission"
            )
        }
        /// Namespace for "SetLocation" metadata.
        public enum SetLocation: Sendable {
            /// Request type for "SetLocation".
            public typealias Input = MobileTesting_SetLocationRequest
            /// Response type for "SetLocation".
            public typealias Output = MobileTesting_ActionResponse
            /// Descriptor for "SetLocation".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "mobile.testing.v1.HostDeviceService"),
                method: "SetLocation"
            )
        }
        /// Namespace for "ClearLocation" metadata.
        public enum ClearLocation: Sendable {
            /// Request type for "ClearLocation".
            public typealias Input = MobileTesting_Empty
            /// Response type for "ClearLocation".
            public typealias Output = MobileTesting_ActionResponse
            /// Descriptor for "ClearLocation".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "mobile.testing.v1.HostDeviceService"),
                method: "ClearLocation"
            )
        }
        /// Namespace for "SetAppearance" metadata.
        public enum SetAppearance: Sendable {
            /// Request type for "SetAppearance".
            public typealias Input = MobileTesting_SetAppearanceRequest
            /// Response type for "SetAppearance".
            public typealias Output = MobileTesting_ActionResponse
            /// Descriptor for "SetAppearance".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "mobile.testing.v1.HostDeviceService"),
                method: "SetAppearance"
            )
        }
        /// Namespace for "OpenURL" metadata.
        public enum OpenURL: Sendable {
            /// Request type for "OpenURL".
            public typealias Input = MobileTesting_OpenURLRequest
            /// Response type for "OpenURL".
            public typealias Output = MobileTesting_ActionResponse
            /// Descriptor for "OpenURL".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "mobile.testing.v1.HostDeviceService"),
                method: "OpenURL"
            )
        }
        /// Descriptors for all methods in the "mobile.testing.v1.HostDeviceService" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            InstallApp.descriptor,
            LaunchApp.descriptor,
            TerminateApp.descriptor,
            UninstallApp.descriptor,
            SetPermission.descriptor,
            SetLocation.descriptor,
            ClearLocation.descriptor,
            SetAppearance.descriptor,
            OpenURL.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "mobile.testing.v1.HostDeviceService" service.
    public static let mobileTesting_HostDeviceService = GRPCCore.ServiceDescriptor(fullyQualifiedService: "mobile.testing.v1.HostDeviceService")
}

// MARK: mobile.testing.v1.HostDeviceService (server)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension MobileTesting_HostDeviceService {
    /// Streaming variant of the service protocol for the "mobile.testing.v1.HostDeviceService" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    public protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "InstallApp" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `MobileTesting_InstallAppRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `MobileTesting_ActionResponse` messages.
        func installApp(
            request: GRPCCore.StreamingServerRequest<MobileTesting_InstallAppRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<MobileTesting_ActionResponse>

        /// Handle the "LaunchApp" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `MobileTesting_LaunchAppRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `MobileTesting_ActionResponse` messages.
        func launchApp(
            request: GRPCCore.StreamingServerRequest<MobileTesting_LaunchAppRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<MobileTesting_ActionResponse>

        /// Handle the "TerminateApp" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `MobileTesting_TerminateAppRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `MobileTesting_ActionResponse` messages.
        func terminateApp(
            request: GRPCCore.StreamingServerRequest<MobileTesting_TerminateAppRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<MobileTesting_ActionResponse>

        /// Handle the "UninstallApp" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `MobileTesting_UninstallAppRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `MobileTesting_ActionResponse` messages.
        func uninstallApp(
            request: GRPCCore.StreamingServerRequest<MobileTesting_UninstallAppRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<MobileTesting_ActionResponse>

        /// Handle the "SetPermission" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `MobileTesting_SetPermissionRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `MobileTesting_ActionResponse` messages.
        func setPermission(
            request: GRPCCore.StreamingServerRequest<MobileTesting_SetPermissionRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<MobileTesting_ActionResponse>

        /// Handle the "SetLocation" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `MobileTesting_SetLocationRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `MobileTesting_ActionResponse` messages.
        func setLocation(
            request: GRPCCore.StreamingServerRequest<MobileTesting_SetLocationRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<MobileTesting_ActionResponse>

        /// Handle the "ClearLocation" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `MobileTesting_Empty` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `MobileTesting_ActionResponse` messages.
        func clearLocation(
            request: GRPCCore.StreamingServerRequest<MobileTesting_Empty>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<MobileTesting_ActionResponse>

        /// Handle the "SetAppearance" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `MobileTesting_SetAppearanceRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `MobileTesting_ActionResponse` messages.
        func setAppearance(
            request: GRPCCore.StreamingServerRequest<MobileTesting_SetAppearanceRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<MobileTesting_ActionResponse>

        /// Handle the "OpenURL" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `MobileTesting_OpenURLRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `MobileTesting_ActionResponse` messages.
        func openURL(
            request: GRPCCore.StreamingServerRequest<MobileTesting_OpenURLRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<MobileTesting_ActionResponse>
    }

    /// Service protocol for the "mobile.testing.v1.HostDeviceService" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    public protocol ServiceProtocol: MobileTesting_HostDeviceService.StreamingServiceProtocol {
        /// Handle the "InstallApp" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `MobileTesting_InstallAppRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `MobileTesting_ActionResponse` message.
        func installApp(
            request: GRPCCore.ServerRequest<MobileTesting_InstallAppRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<MobileTesting_ActionResponse>

        /// Handle the "LaunchApp" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `MobileTesting_LaunchAppRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `MobileTesting_ActionResponse` message.
        func launchApp(
            request: GRPCCore.ServerRequest<MobileTesting_LaunchAppRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<MobileTesting_ActionResponse>

        /// Handle the "TerminateApp" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `MobileTesting_TerminateAppRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `MobileTesting_ActionResponse` message.
        func terminateApp(
            request: GRPCCore.ServerRequest<MobileTesting_TerminateAppRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<MobileTesting_ActionResponse>

        /// Handle the "UninstallApp" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `MobileTesting_UninstallAppRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `MobileTesting_ActionResponse` message.
        func uninstallApp(
            request: GRPCCore.ServerRequest<MobileTesting_UninstallAppRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<MobileTesting_ActionResponse>

        /// Handle the "SetPermission" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `MobileTesting_SetPermissionRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `MobileTesting_ActionResponse` message.
        func setPermission(
            request: GRPCCore.ServerRequest<MobileTesting_SetPermissionRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<MobileTesting_ActionResponse>

        /// Handle the "SetLocation" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `MobileTesting_SetLocationRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `MobileTesting_ActionResponse` message.
        func setLocation(
            request: GRPCCore.ServerRequest<MobileTesting_SetLocationRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<MobileTesting_ActionResponse>

        /// Handle the "ClearLocation" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `MobileTesting_Empty` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `MobileTesting_ActionResponse` message.
        func clearLocation(
            request: GRPCCore.ServerRequest<MobileTesting_Empty>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<MobileTesting_ActionResponse>

        /// Handle the "SetAppearance" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `MobileTesting_SetAppearanceRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `MobileTesting_ActionResponse` message.
        func setAppearance(
            request: GRPCCore.ServerRequest<MobileTesting_SetAppearanceRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<MobileTesting_ActionResponse>

        /// Handle the "OpenURL" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `MobileTesting_OpenURLRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `MobileTesting_ActionResponse` message.
        func openURL(
            request: GRPCCore.ServerRequest<MobileTesting_OpenURLRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<MobileTesting_ActionResponse>
    }

    /// Simple service protocol for the "mobile.testing.v1.HostDeviceService" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    public protocol SimpleServiceProtocol: MobileTesting_HostDeviceService.ServiceProtocol {
        /// Handle the "InstallApp" method.
        ///
        /// - Parameters:
        ///   - request: A `MobileTesting_InstallAppRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `MobileTesting_ActionResponse` to respond with.
        func installApp(
            request: MobileTesting_InstallAppRequest,
            context: GRPCCore.ServerContext
        ) async throws -> MobileTesting_ActionResponse

        /// Handle the "LaunchApp" method.
        ///
        /// - Parameters:
        ///   - request: A `MobileTesting_LaunchAppRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `MobileTesting_ActionResponse` to respond with.
        func launchApp(
            request: MobileTesting_LaunchAppRequest,
            context: GRPCCore.ServerContext
        ) async throws -> MobileTesting_ActionResponse

        /// Handle the "TerminateApp" method.
        ///
        /// - Parameters:
        ///   - request: A `MobileTesting_TerminateAppRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `MobileTesting_ActionResponse` to respond with.
        func terminateApp(
            request: MobileTesting_TerminateAppRequest,
            context: GRPCCore.ServerContext
        ) async throws -> MobileTesting_ActionResponse

        /// Handle the "UninstallApp" method.
        ///
        /// - Parameters:
        ///   - request: A `MobileTesting_UninstallAppRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `MobileTesting_ActionResponse` to respond with.
        func uninstallApp(
            request: MobileTesting_UninstallAppRequest,
            context: GRPCCore.ServerContext
        ) async throws -> MobileTesting_ActionResponse

        /// Handle the "SetPermission" method.
        ///
        /// - Parameters:
        ///   - request: A `MobileTesting_SetPermissionRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `MobileTesting_ActionResponse` to respond with.
        func setPermission(
            request: MobileTesting_SetPermissionRequest,
            context: GRPCCore.ServerContext
        ) async throws -> MobileTesting_ActionResponse

        /// Handle the "SetLocation" method.
        ///
        /// - Parameters:
        ///   - request: A `MobileTesting_SetLocationRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `MobileTesting_ActionResponse` to respond with.
        func setLocation(
            request: MobileTesting_SetLocationRequest,
            context: GRPCCore.ServerContext
        ) async throws -> MobileTesting_ActionResponse

        /// Handle the "ClearLocation" method.
        ///
        /// - Parameters:
        ///   - request: A `MobileTesting_Empty` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `MobileTesting_ActionResponse` to respond with.
        func clearLocation(
            request: MobileTesting_Empty,
            context: GRPCCore.ServerContext
        ) async throws -> MobileTesting_ActionResponse

        /// Handle the "SetAppearance" method.
        ///
        /// - Parameters:
        ///   - request: A `MobileTesting_SetAppearanceRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `MobileTesting_ActionResponse` to respond with.
        func setAppearance(
            request: MobileTesting_SetAppearanceRequest,
            context: GRPCCore.ServerContext
        ) async throws -> MobileTesting_ActionResponse

        /// Handle the "OpenURL" method.
        ///
        /// - Parameters:
        ///   - request: A `MobileTesting_OpenURLRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `MobileTesting_ActionResponse` to respond with.
        func openURL(
            request: MobileTesting_OpenURLRequest,
            context: GRPCCore.ServerContext
        ) async throws -> MobileTesting_ActionResponse
    }
}

// Default implementation of 'registerMethods(with:)'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension MobileTesting_HostDeviceService.StreamingServiceProtocol {
    public func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: MobileTesting_HostDeviceService.Method.InstallApp.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<MobileTesting_InstallAppRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<MobileTesting_ActionResponse>(),
            handler: { request, context in
                try await self.installApp(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: MobileTesting_HostDeviceService.Method.LaunchApp.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<MobileTesting_LaunchAppRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<MobileTesting_ActionResponse>(),
            handler: { request, context in
                try await self.launchApp(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: MobileTesting_HostDeviceService.Method.TerminateApp.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<MobileTesting_TerminateAppRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<MobileTesting_ActionResponse>(),
            handler: { request, context in
                try await self.terminateApp(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: MobileTesting_HostDeviceService.Method.UninstallApp.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<MobileTesting_UninstallAppRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<MobileTesting_ActionResponse>(),
            handler: { request, context in
                try await self.uninstallApp(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: MobileTesting_HostDeviceService.Method.SetPermission.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<MobileTesting_SetPermissionRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<MobileTesting_ActionResponse>(),
            handler: { request, context in
                try await self.setPermission(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: MobileTesting_HostDeviceService.Method.SetLocation.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<MobileTesting_SetLocationRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<MobileTesting_ActionResponse>(),
            handler: { request, context in
                try await self.setLocation(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: MobileTesting_HostDeviceService.Method.ClearLocation.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<MobileTesting_Empty>(),
            serializer: GRPCProtobuf.ProtobufSerializer<MobileTesting_ActionResponse>(),
            handler: { request, context in
                try await self.clearLocation(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: MobileTesting_HostDeviceService.Method.SetAppearance.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<MobileTesting_SetAppearanceRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<MobileTesting_ActionResponse>(),
            handler: { request, context in
                try await self.setAppearance(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: MobileTesting_HostDeviceService.Method.OpenURL.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<MobileTesting_OpenURLRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<MobileTesting_ActionResponse>(),
            handler: { request, context in
                try await self.openURL(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension MobileTesting_HostDeviceService.ServiceProtocol {
    public func installApp(
        request: GRPCCore.StreamingServerRequest<MobileTesting_InstallAppRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<MobileTesting_ActionResponse> {
        let response = try await self.installApp(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func launchApp(
        request: GRPCCore.StreamingServerRequest<MobileTesting_LaunchAppRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<MobileTesting_ActionResponse> {
        let response = try await self.launchApp(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func terminateApp(
        request: GRPCCore.StreamingServerRequest<MobileTesting_TerminateAppRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<MobileTesting_ActionResponse> {
        let response = try await self.terminateApp(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func uninstallApp(
        request: GRPCCore.StreamingServerRequest<MobileTesting_UninstallAppRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<MobileTesting_ActionResponse> {
        let response = try await self.uninstallApp(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func setPermission(
        request: GRPCCore.StreamingServerRequest<MobileTesting_SetPermissionRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<MobileTesting_ActionResponse> {
        let response = try await self.setPermission(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func setLocation(
        request: GRPCCore.StreamingServerRequest<MobileTesting_SetLocationRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<MobileTesting_ActionResponse> {
        let response = try await self.setLocation(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func clearLocation(
        request: GRPCCore.StreamingServerRequest<MobileTesting_Empty>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<MobileTesting_ActionResponse> {
        let response = try await self.clearLocation(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func setAppearance(
        request: GRPCCore.StreamingServerRequest<MobileTesting_SetAppearanceRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<MobileTesting_ActionResponse> {
        let response = try await self.setAppearance(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func openURL(
        request: GRPCCore.StreamingServerRequest<MobileTesting_OpenURLRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<MobileTesting_ActionResponse> {
        let response = try await self.openURL(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }
}

// Default implementation of methods from 'ServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension MobileTesting_HostDeviceService.SimpleServiceProtocol {
    public func installApp(
        request: GRPCCore.ServerRequest<MobileTesting_InstallAppRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<MobileTesting_ActionResponse> {
        return GRPCCore.ServerResponse<MobileTesting_ActionResponse>(
            message: try await self.installApp(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func launchApp(
        request: GRPCCore.ServerRequest<MobileTesting_LaunchAppRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<MobileTesting_ActionResponse> {
        return GRPCCore.ServerResponse<MobileTesting_ActionResponse>(
            message: try await self.launchApp(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func terminateApp(
        request: GRPCCore.ServerRequest<MobileTesting_TerminateAppRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<MobileTesting_ActionResponse> {
        return GRPCCore.ServerResponse<MobileTesting_ActionResponse>(
            message: try await self.terminateApp(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func uninstallApp(
        request: GRPCCore.ServerRequest<MobileTesting_UninstallAppRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<MobileTesting_ActionResponse> {
        return GRPCCore.ServerResponse<MobileTesting_ActionResponse>(
            message: try await self.uninstallApp(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func setPermission(
        request: GRPCCore.ServerRequest<MobileTesting_SetPermissionRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<MobileTesting_ActionResponse> {
        return GRPCCore.ServerResponse<MobileTesting_ActionResponse>(
            message: try await self.setPermission(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func setLocation(
        request: GRPCCore.ServerRequest<MobileTesting_SetLocationRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<MobileTesting_ActionResponse> {
        return GRPCCore.ServerResponse<MobileTesting_ActionResponse>(
            message: try await self.setLocation(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func clearLocation(
        request: GRPCCore.ServerRequest<MobileTesting_Empty>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<MobileTesting_ActionResponse> {
        return GRPCCore.ServerResponse<MobileTesting_ActionResponse>(
            message: try await self.clearLocation(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func setAppearance(
        request: GRPCCore.ServerRequest<MobileTesting_SetAppearanceRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<MobileTesting_ActionResponse> {
        return GRPCCore.ServerResponse<MobileTesting_ActionResponse>(
            message: try await self.setAppearance(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func openURL(
        request: GRPCCore.ServerRequest<MobileTesting_OpenURLRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<MobileTesting_ActionResponse> {
        return GRPCCore.ServerResponse<MobileTesting_ActionResponse>(
            message: try await self.openURL(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }
}

// MARK: mobile.testing.v1.HostDeviceService (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension MobileTesting_HostDeviceService {
    /// Generated client protocol for the "mobile.testing.v1.HostDeviceService" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    public protocol ClientProtocol: Sendable {
        /// Call the "InstallApp" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `MobileTesting_InstallAppRequest` message.
        ///   - serializer: A serializer for `MobileTesting_InstallAppRequest` messages.
        ///   - deserializer: A deserializer for `MobileTesting_ActionResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func installApp<Result>(
            request: GRPCCore.ClientRequest<MobileTesting_InstallAppRequest>,
            serializer: some GRPCCore.MessageSerializer<MobileTesting_InstallAppRequest>,
            deserializer: some GRPCCore.MessageDeserializer<MobileTesting_ActionResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<MobileTesting_ActionResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "LaunchApp" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `MobileTesting_LaunchAppRequest` message.
        ///   - serializer: A serializer for `MobileTesting_LaunchAppRequest` messages.
        ///   - deserializer: A deserializer for `MobileTesting_ActionResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func launchApp<Result>(
            request: GRPCCore.ClientRequest<MobileTesting_LaunchAppRequest>,
            serializer: some GRPCCore.MessageSerializer<MobileTesting_LaunchAppRequest>,
            deserializer: some GRPCCore.MessageDeserializer<MobileTesting_ActionResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<MobileTesting_ActionResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "TerminateApp" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `MobileTesting_TerminateAppRequest` message.
        ///   - serializer: A serializer for `MobileTesting_TerminateAppRequest` messages.
        ///   - deserializer: A deserializer for `MobileTesting_ActionResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func terminateApp<Result>(
            request: GRPCCore.ClientRequest<MobileTesting_TerminateAppRequest>,
            serializer: some GRPCCore.MessageSerializer<MobileTesting_TerminateAppRequest>,
            deserializer: some GRPCCore.MessageDeserializer<MobileTesting_ActionResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<MobileTesting_ActionResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "UninstallApp" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `MobileTesting_UninstallAppRequest` message.
        ///   - serializer: A serializer for `MobileTesting_UninstallAppRequest` messages.
        ///   - deserializer: A deserializer for `MobileTesting_ActionResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func uninstallApp<Result>(
            request: GRPCCore.ClientRequest<MobileTesting_UninstallAppRequest>,
            serializer: some GRPCCore.MessageSerializer<MobileTesting_UninstallAppRequest>,
            deserializer: some GRPCCore.MessageDeserializer<MobileTesting_ActionResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<MobileTesting_ActionResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "SetPermission" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `MobileTesting_SetPermissionRequest` message.
        ///   - serializer: A serializer for `MobileTesting_SetPermissionRequest` messages.
        ///   - deserializer: A deserializer for `MobileTesting_ActionResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func setPermission<Result>(
            request: GRPCCore.ClientRequest<MobileTesting_SetPermissionRequest>,
            serializer: some GRPCCore.MessageSerializer<MobileTesting_SetPermissionRequest>,
            deserializer: some GRPCCore.MessageDeserializer<MobileTesting_ActionResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<MobileTesting_ActionResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "SetLocation" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `MobileTesting_SetLocationRequest` message.
        ///   - serializer: A serializer for `MobileTesting_SetLocationRequest` messages.
        ///   - deserializer: A deserializer for `MobileTesting_ActionResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func setLocation<Result>(
            request: GRPCCore.ClientRequest<MobileTesting_SetLocationRequest>,
            serializer: some GRPCCore.MessageSerializer<MobileTesting_SetLocationRequest>,
            deserializer: some GRPCCore.MessageDeserializer<MobileTesting_ActionResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<MobileTesting_ActionResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "ClearLocation" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `MobileTesting_Empty` message.
        ///   - serializer: A serializer for `MobileTesting_Empty` messages.
        ///   - deserializer: A deserializer for `MobileTesting_ActionResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func clearLocation<Result>(
            request: GRPCCore.ClientRequest<MobileTesting_Empty>,
            serializer: some GRPCCore.MessageSerializer<MobileTesting_Empty>,
            deserializer: some GRPCCore.MessageDeserializer<MobileTesting_ActionResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<MobileTesting_ActionResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "SetAppearance" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `MobileTesting_SetAppearanceRequest` message.
        ///   - serializer: A serializer for `MobileTesting_SetAppearanceRequest` messages.
        ///   - deserializer: A deserializer for `MobileTesting_ActionResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func setAppearance<Result>(
            request: GRPCCore.ClientRequest<MobileTesting_SetAppearanceRequest>,
            serializer: some GRPCCore.MessageSerializer<MobileTesting_SetAppearanceRequest>,
            deserializer: some GRPCCore.MessageDeserializer<MobileTesting_ActionResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<MobileTesting_ActionResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "OpenURL" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `MobileTesting_OpenURLRequest` message.
        ///   - serializer: A serializer for `MobileTesting_OpenURLRequest` messages.
        ///   - deserializer: A deserializer for `MobileTesting_ActionResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func openURL<Result>(
            request: GRPCCore.ClientRequest<MobileTesting_OpenURLRequest>,
            serializer: some GRPCCore.MessageSerializer<MobileTesting_OpenURLRequest>,
            deserializer: some GRPCCore.MessageDeserializer<MobileTesting_ActionResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<MobileTesting_ActionResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "mobile.testing.v1.HostDeviceService" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "InstallApp" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `MobileTesting_InstallAppRequest` message.
        ///   - serializer: A serializer for `MobileTesting_InstallAppRequest` messages.
        ///   - deserializer: A deserializer for `MobileTesting_ActionResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func installApp<Result>(
            request: GRPCCore.ClientRequest<MobileTesting_InstallAppRequest>,
            serializer: some GRPCCore.MessageSerializer<MobileTesting_InstallAppRequest>,
            deserializer: some GRPCCore.MessageDeserializer<MobileTesting_ActionResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<MobileTesting_ActionResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: MobileTesting_HostDeviceService.Method.InstallApp.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "LaunchApp" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `MobileTesting_LaunchAppRequest` message.
        ///   - serializer: A serializer for `MobileTesting_LaunchAppRequest` messages.
        ///   - deserializer: A deserializer for `MobileTesting_ActionResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func launchApp<Result>(
            request: GRPCCore.ClientRequest<MobileTesting_LaunchAppRequest>,
            serializer: some GRPCCore.MessageSerializer<MobileTesting_LaunchAppRequest>,
            deserializer: some GRPCCore.MessageDeserializer<MobileTesting_ActionResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<MobileTesting_ActionResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: MobileTesting_HostDeviceService.Method.LaunchApp.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "TerminateApp" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `MobileTesting_TerminateAppRequest` message.
        ///   - serializer: A serializer for `MobileTesting_TerminateAppRequest` messages.
        ///   - deserializer: A deserializer for `MobileTesting_ActionResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func terminateApp<Result>(
            request: GRPCCore.ClientRequest<MobileTesting_TerminateAppRequest>,
            serializer: some GRPCCore.MessageSerializer<MobileTesting_TerminateAppRequest>,
            deserializer: some GRPCCore.MessageDeserializer<MobileTesting_ActionResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<MobileTesting_ActionResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: MobileTesting_HostDeviceService.Method.TerminateApp.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "UninstallApp" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `MobileTesting_UninstallAppRequest` message.
        ///   - serializer: A serializer for `MobileTesting_UninstallAppRequest` messages.
        ///   - deserializer: A deserializer for `MobileTesting_ActionResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func uninstallApp<Result>(
            request: GRPCCore.ClientRequest<MobileTesting_UninstallAppRequest>,
            serializer: some GRPCCore.MessageSerializer<MobileTesting_UninstallAppRequest>,
            deserializer: some GRPCCore.MessageDeserializer<MobileTesting_ActionResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<MobileTesting_ActionResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: MobileTesting_HostDeviceService.Method.UninstallApp.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "SetPermission" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `MobileTesting_SetPermissionRequest` message.
        ///   - serializer: A serializer for `MobileTesting_SetPermissionRequest` messages.
        ///   - deserializer: A deserializer for `MobileTesting_ActionResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func setPermission<Result>(
            request: GRPCCore.ClientRequest<MobileTesting_SetPermissionRequest>,
            serializer: some GRPCCore.MessageSerializer<MobileTesting_SetPermissionRequest>,
            deserializer: some GRPCCore.MessageDeserializer<MobileTesting_ActionResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<MobileTesting_ActionResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: MobileTesting_HostDeviceService.Method.SetPermission.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "SetLocation" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `MobileTesting_SetLocationRequest` message.
        ///   - serializer: A serializer for `MobileTesting_SetLocationRequest` messages.
        ///   - deserializer: A deserializer for `MobileTesting_ActionResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func setLocation<Result>(
            request: GRPCCore.ClientRequest<MobileTesting_SetLocationRequest>,
            serializer: some GRPCCore.MessageSerializer<MobileTesting_SetLocationRequest>,
            deserializer: some GRPCCore.MessageDeserializer<MobileTesting_ActionResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<MobileTesting_ActionResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: MobileTesting_HostDeviceService.Method.SetLocation.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "ClearLocation" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `MobileTesting_Empty` message.
        ///   - serializer: A serializer for `MobileTesting_Empty` messages.
        ///   - deserializer: A deserializer for `MobileTesting_ActionResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func clearLocation<Result>(
            request: GRPCCore.ClientRequest<MobileTesting_Empty>,
            serializer: some GRPCCore.MessageSerializer<MobileTesting_Empty>,
            deserializer: some GRPCCore.MessageDeserializer<MobileTesting_ActionResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<MobileTesting_ActionResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: MobileTesting_HostDeviceService.Method.ClearLocation.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "SetAppearance" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `MobileTesting_SetAppearanceRequest` message.
        ///   - serializer: A serializer for `MobileTesting_SetAppearanceRequest` messages.
        ///   - deserializer: A deserializer for `MobileTesting_ActionResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func setAppearance<Result>(
            request: GRPCCore.ClientRequest<MobileTesting_SetAppearanceRequest>,
            serializer: some GRPCCore.MessageSerializer<MobileTesting_SetAppearanceRequest>,
            deserializer: some GRPCCore.MessageDeserializer<MobileTesting_ActionResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<MobileTesting_ActionResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: MobileTesting_HostDeviceService.Method.SetAppearance.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "OpenURL" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `MobileTesting_OpenURLRequest` message.
        ///   - serializer: A serializer for `MobileTesting_OpenURLRequest` messages.
        ///   - deserializer: A deserializer for `MobileTesting_ActionResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func openURL<Result>(
            request: GRPCCore.ClientRequest<MobileTesting_OpenURLRequest>,
            serializer: some GRPCCore.MessageSerializer<MobileTesting_OpenURLRequest>,
            deserializer: some GRPCCore.MessageDeserializer<MobileTesting_ActionResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<MobileTesting_ActionResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: MobileTesting_HostDeviceService.Method.OpenURL.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension MobileTesting_HostDeviceService.ClientProtocol {
    /// Call the "InstallApp" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `MobileTesting_InstallAppRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func installApp<Result>(
        request: GRPCCore.ClientRequest<MobileTesting_InstallAppRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<MobileTesting_ActionResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.installApp(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<MobileTesting_InstallAppRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<MobileTesting_ActionResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "LaunchApp" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `MobileTesting_LaunchAppRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func launchApp<Result>(
        request: GRPCCore.ClientRequest<MobileTesting_LaunchAppRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<MobileTesting_ActionResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.launchApp(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<MobileTesting_LaunchAppRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<MobileTesting_ActionResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "TerminateApp" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `MobileTesting_TerminateAppRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func terminateApp<Result>(
        request: GRPCCore.ClientRequest<MobileTesting_TerminateAppRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<MobileTesting_ActionResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.terminateApp(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<MobileTesting_TerminateAppRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<MobileTesting_ActionResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "UninstallApp" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `MobileTesting_UninstallAppRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func uninstallApp<Result>(
        request: GRPCCore.ClientRequest<MobileTesting_UninstallAppRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<MobileTesting_ActionResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.uninstallApp(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<MobileTesting_UninstallAppRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<MobileTesting_ActionResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "SetPermission" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `MobileTesting_SetPermissionRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func setPermission<Result>(
        request: GRPCCore.ClientRequest<MobileTesting_SetPermissionRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<MobileTesting_ActionResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.setPermission(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<MobileTesting_SetPermissionRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<MobileTesting_ActionResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "SetLocation" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `MobileTesting_SetLocationRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func setLocation<Result>(
        request: GRPCCore.ClientRequest<MobileTesting_SetLocationRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<MobileTesting_ActionResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.setLocation(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<MobileTesting_SetLocationRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<MobileTesting_ActionResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ClearLocation" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `MobileTesting_Empty` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func clearLocation<Result>(
        request: GRPCCore.ClientRequest<MobileTesting_Empty>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<MobileTesting_ActionResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.clearLocation(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<MobileTesting_Empty>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<MobileTesting_ActionResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "SetAppearance" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `MobileTesting_SetAppearanceRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func setAppearance<Result>(
        request: GRPCCore.ClientRequest<MobileTesting_SetAppearanceRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<MobileTesting_ActionResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.setAppearance(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<MobileTesting_SetAppearanceRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<MobileTesting_ActionResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "OpenURL" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `MobileTesting_OpenURLRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func openURL<Result>(
        request: GRPCCore.ClientRequest<MobileTesting_OpenURLRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<MobileTesting_ActionResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.openURL(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<MobileTesting_OpenURLRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<MobileTesting_ActionResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension MobileTesting_HostDeviceService.ClientProtocol {
    /// Call the "InstallApp" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func installApp<Result>(
        _ message: MobileTesting_InstallAppRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<MobileTesting_ActionResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<MobileTesting_InstallAppRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.installApp(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "LaunchApp" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func launchApp<Result>(
        _ message: MobileTesting_LaunchAppRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<MobileTesting_ActionResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<MobileTesting_LaunchAppRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.launchApp(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "TerminateApp" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func terminateApp<Result>(
        _ message: MobileTesting_TerminateAppRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<MobileTesting_ActionResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<MobileTesting_TerminateAppRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.terminateApp(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "UninstallApp" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func uninstallApp<Result>(
        _ message: MobileTesting_UninstallAppRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<MobileTesting_ActionResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<MobileTesting_UninstallAppRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.uninstallApp(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "SetPermission" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func setPermission<Result>(
        _ message: MobileTesting_SetPermissionRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<MobileTesting_ActionResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<MobileTesting_SetPermissionRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.setPermission(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "SetLocation" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func setLocation<Result>(
        _ message: MobileTesting_SetLocationRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<MobileTesting_ActionResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<MobileTesting_SetLocationRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.setLocation(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ClearLocation" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func clearLocation<Result>(
        _ message: MobileTesting_Empty,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<MobileTesting_ActionResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<MobileTesting_Empty>(
            message: message,
            metadata: metadata
        )
        return try await self.clearLocation(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "SetAppearance" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func setAppearance<Result>(
        _ message: MobileTesting_SetAppearanceRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<MobileTesting_ActionResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<MobileTesting_SetAppearanceRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.setAppearance(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "OpenURL" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func openURL<Result>(
        _ message: MobileTesting_OpenURLRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<MobileTesting_ActionResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<MobileTesting_OpenURLRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.openURL(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}